---
title: "Ejercicios de Límite"
subtitle: "Cálculo"
author: "http://synergy.vision/"
output:
  pdf_document:
      toc: yes
      toc_depth: 4
      includes:
        in_header: ./preambulo.tex
  html_document: default
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newpage

# LIMITES 

1. $\displaystyle\lim_{x\to 2}\frac{x^2+6}{x^2-3}$



2. $\displaystyle\lim_{y\to 0}\left[\frac{y^2-2y+2}{y-4}+1 \right ]$



3. $\displaystyle\lim_{x\to\sqrt{2}}\frac{x^2-2}{x^4+x+1}$



4. $\displaystyle\lim_{x\to 1}\sqrt\frac{2x^2+2}{8x^2+1}$



5. $\displaystyle\lim_{x\to 3}\frac{x^2-9}{x-3}$



6. $\displaystyle\lim_{y\to -5}\frac{y^2-25}{y+5}$



7. $\displaystyle\lim_{h\to 2}\frac{h-2}{h^2-4}$



8. $\displaystyle\lim_{x\to 2}\frac{x^3-8}{x-2}$



9. $\displaystyle\lim_{y\to -3}\frac{y^3+27}{y+3}$



10. $\displaystyle\lim_{x\to 4}\frac{x^2+4x-32}{x-4}$



11. $\displaystyle\lim_{x\to -1}\frac{\frac{1}{2}x^2 -\frac{5}{2}x-3}{x+1}$



12. $\displaystyle\lim_{x\to -2}\frac{\frac{1}{x+1}+1}{x+2}$



13. $\displaystyle\lim_{x\to \frac{1}{2}}\frac{8x^3-1}{6x^2-5x+1}$



14. $\displaystyle\lim_{x\to 2}\frac{x^4-16}{x-2}$



15. $\displaystyle\lim_{x\to 8}\frac{16-x^{4/3}}{4-x^{2/3}}$



16. $\displaystyle\lim_{x\to 2}\frac{\sqrt{x^2+5}-3}{x^2-2x}$



17. $\displaystyle\lim_{x\to 9}\frac{x^2-81}{\sqrt{x}-3}$



18. $\displaystyle\lim_{x\to 0}\frac{x}{\sqrt{x+2}-{\sqrt{2}}}$



19. $\displaystyle\lim_{y\to 0}\frac{\sqrt{y+3}-\sqrt{3}}{y}$



20. $\displaystyle\lim_{x\to 1}\frac{\sqrt{x+3}-2}{x-1}$



21. $\displaystyle\lim_{y\to 5}\frac{\sqrt{y-1}-2}{y+5}$



22. $\displaystyle\lim_{h\to 0}\frac{\sqrt{1+h^2}-1}{h}$



23. $\displaystyle\lim_{x\to 7}\frac{2-\sqrt{x-3}}{x^2-49}$



24. $\displaystyle\lim_{x\to 1}\frac{x^2-\sqrt{x}}{\sqrt{x}-1}$



25. $\displaystyle\lim_{x\to 0} \frac{\sqrt{1+x}-\sqrt{1-x}}{\sqrt[3]{1+x}-{\sqrt[3]1-x}}$



26. $\displaystyle\lim_{x\to 8}\frac{x-8}{\sqrt[3]{x}{-2}}$



27. $\displaystyle\lim_{x\to 0}\frac{\sqrt[3]{x^2+1}-1}{x^2}$



28. $\displaystyle\lim_{x\to 0}\frac{\sqrt[3]{1+x}-\sqrt[3]{1-x}}{x}$



29. $\displaystyle\lim_{x\to 1}\frac{\sqrt{x}-{1}}{\sqrt[3]{x}-1}$



30. $\displaystyle\lim_{x\to 64}\frac{\sqrt{x}-{8}}{\sqrt[3]{x}-{4}}$



31. $\displaystyle\lim_{x\to 1}\frac{\sqrt[3]{x}-{1}}{\sqrt[4]{x}-{1}}$



32. $\displaystyle\lim_{x\to 1}\frac{\sqrt[n]{x}-{1}}{\sqrt[m]{x}-{1}}$



33. $\displaystyle\lim_{x\to 2}\frac{\sqrt{6-x}-{2}}{\sqrt{3-x}-{1}}$



34. $\displaystyle\lim_{x\to a}\frac{x^3-a^3}{x^2-ax-x+a}$



35. $\displaystyle\lim_{x\to 1} \frac{\sqrt{ax+b}-\sqrt{bx+a}}{\sqrt{cx+d}-\sqrt{dx+c}}$



36. Si $f(x)=\frac{1}{x},\quad x\ne0,\text{probar que}$ 

$\displaystyle\lim_{h\to 0}\frac{g(x+h)-g(x)}{h}=-\frac{1}{x^2}$


37. Si $f(x)=\sqrt{x},\quad x>0,\text{probar que}$ 

$\displaystyle\lim_{h\to 0}\frac{f(x+h)-f(x)}{h}=\frac{1}{2\sqrt{x}}$


38. $\displaystyle\lim_{x\to 2^+}\frac{\sqrt{x-2}}{2x-1}$


39. $\displaystyle\lim_{x\to 4^+}\frac{x-4}{\sqrt{x^2-16}}$


40. $\displaystyle\lim_{x\to 2^-}[x]$


41. $\displaystyle\lim_{x\to 2^+}[x]$


42. $\displaystyle\lim_{x\to -2^-}[x]$


43. $\displaystyle\lim_{x\to -2^+}[x]$


44. $\displaystyle\lim_{x\to 5/2}[x]$


45. $\displaystyle\lim_{x\to 2^-}(x-[x])$


46. $\displaystyle\lim_{x\to 2^+}(x-[x])$


47. $\displaystyle\lim_{x\to 3^-}[x^2+x+1]$


48. $\displaystyle\lim_{x\to 3^+}[x^2+x+1]$


49. $\displaystyle\lim_{x\to 3^-}\big[[x]+[4-x]\big]$


50. $\displaystyle\lim_{x\to 3^+}\big[[x]+[4-x]\big]$


51. $\displaystyle\lim_{x\to 4^+}\frac{x-4}{|x-4|}$


52. $\displaystyle\lim_{x\to 1^+}\frac{\sqrt{x+4}-\sqrt{4x+1}}{\sqrt{x-1}}$


53. $\displaystyle\lim_{x\to a^+} \frac{\sqrt{4-x^2}+2-x}{\sqrt{4-x^3/2}+\sqrt{2x-x^2}}$


54. $\displaystyle\lim_{x\to a^+} \frac{x\sqrt{x}-a\sqrt{a}}{\sqrt[3]{x}-\sqrt[3]{a}}$


55. Si $h(x)=$ 
$\left\{\begin{matrix}
2x+1 &\text{si}\ x\le2\\
x^2+1 &\text{si}\ x>2
\end{matrix}
\right.$

Hallar:

a. $\displaystyle\lim_{x\to 2^-}h(x)$

b. $\displaystyle\lim_{x\to 2^+}h(x)$

c. $\displaystyle\lim_{x\to 2}h(x)$


56. Si $f(x)=$ 
$\left\{\begin{matrix}
x^3,  &\text{si}\ x\le2\\
x^2+4, &\text{si}\ x>2
\end{matrix}
\right.$

Hallar:

a. $\displaystyle\lim_{x\to 2^-}f(x)$

b. $\displaystyle\lim_{x\to 2^+}f(x)$

c. $\displaystyle\lim_{x\to 2}f(x)$


57. Si $f(x)=$ 
$\left\{\begin{matrix}
-4 &\text{si}\ x<-2\\
\displaystyle\frac{x^3}{2}  &\text{si}\ -2\le x<2\\
x-1 &\text{si}\ x\ge 2
\end{matrix}
\right.$

Hallar:

a. $\displaystyle\lim_{x\to -2}f(x)$

b. $\displaystyle\lim_{x\to 2}f(x)$



58. Hallar la función $f$ tal que:

$\displaystyle\lim_{x\to 0^-} f(x)=3$ y que no exista $\displaystyle\lim_{x\to 0^+} f(x)$


59. Pruebe, con un contraejemplo, que las proposiciones siguientes son falsas:

a. Existe $\displaystyle\lim_{x\to a}[f(x)+g(x)]\Rightarrow$ Existe $\displaystyle\lim_{x\to a}f(x)$ y existe $\displaystyle\lim_{x\to a} g(x)$

b. Existe $\displaystyle\lim_{x\to a}[f(x)g(x)]\Rightarrow$ Existe $\displaystyle\lim_{x\to a}f(x)$ y existe $\displaystyle\lim_{x\to a} g(x)$


60. Probar que: existe $\displaystyle\lim_{x\to a}\frac{f(x)}{g(x)}\quad y\quad  \displaystyle\lim_{x\to a}g(x)=0\Rightarrow\displaystyle\lim_{x\to a}f(x)=0$

De esta proposición se obtiene:

$\displaystyle\lim_{x\to a}f(x)\ne0\quad y\quad \displaystyle\lim_{x\to a}g(x)=0\Rightarrow\text{no existe}\displaystyle\lim_{x\to a}\frac{f(x)}{g(x)}$


En los siguientes problemas probar, mediante $\varepsilon\delta$, el límite indicado.

61. $\displaystyle\lim_{x\to 2}(4x-3)=5$

62. $\displaystyle\lim_{t\to 4}(9-3t)=-3$

63. $\displaystyle\lim_{x\to -2}(\frac{x}{5}+1)=\frac{3}{5}$

64. $\displaystyle\lim_{x\to 2}X^2=4$

65. $\displaystyle\lim_{x\to -2}x^3=-8$

66. $\displaystyle\lim_{x\to 1}\frac{x^2-1}{x-1}=2$

67. $\displaystyle\lim_{x\to 1}(x^2+2x-6)=-3$

68. $\displaystyle\lim_{x\to 1}(2x^2+3x-4)=-5$

69. $\displaystyle\lim_{x\to 3}\frac{4}{x-1}=2$

70. $\displaystyle\lim_{x\to 5}\frac{6}{4-x}=-6$

71. $\displaystyle\lim_{x\to 1}\frac{2x}{5-2x}=\frac{2}{3}$

72. $\displaystyle\lim_{x\to 4}\sqrt{x+5}=3$

73. $\displaystyle\lim_{x\to 0}\frac{1}{|x|+1}=1$

74. $\displaystyle\lim_{x\to 1/3}\frac{1+x}{x}=4$

75. $\displaystyle\lim_{x\to a}c=c,$ c es una constante.

76. $\displaystyle\lim_{x\to a}x=a$

77. $\displaystyle\lim_{x\to a}x^n=a^n.$

Sugerencia:$x^n-a^n=(x-a)(x^{n-1}+x^{n-2}a+...+xa^{n-2}+a^{n-1})$

78. $\displaystyle\lim_{x\to a}\frac{1}{x}=\frac{1}{a}$ 

Sugerencia seguir el esquema tomando $\beta=|a|/2$

79. Probar: $\displaystyle\lim_{x\to a}f(x)=L\Rightarrow\displaystyle\lim_{x\to a}|f(x)|=|L|.$

En los siguientes problemas, mediante el teorema del emparedado, probar que:

80. $\displaystyle\lim_{x\to 0}x^2scn\frac{1}{x}=0$

81. $\displaystyle\lim_{x\to 0}\frac{\sqrt{x^2+1}}{|x|+1}=1$

82. $\displaystyle\lim_{x\to9} \left[2-\sqrt{2}cos\left(\frac{1}{x^2}\right)\right]=0$

83. $\displaystyle\lim_{x\to 0}\frac{|x+1|-|x-1|}{\sqrt{3x^2+1}}=0$

En los siguientes problemas hallar el límite indicado.

84. $\displaystyle\lim_{x\to \pi}\frac{senx}{x-\pi}$

85. $\displaystyle\lim_{x\to 0}\frac{sen2x}{sen3x}$

86. $\displaystyle\lim_{x\to 0}\frac{1-cos2x}{4x^2}$

87. $\displaystyle\lim_{x\to \pi/4}[tan2x-sec2x]$

88. $\displaystyle\lim_{t\to 0}\frac{1-cost}{sent}$

89. $\displaystyle\lim_{x\to 0}\frac{sen^2(x/2)}{senx}$

90. $\displaystyle\lim_{x\to 1}\frac{sen^2(x-1)}{x^2-2x+1}$

91. $\displaystyle\lim_{x\to 0}\frac{x-sen2x}{x-sen3x}$

92. $\displaystyle\lim_{x\to 0}\frac{tanx-senx}{x^3}$

93. $\displaystyle\lim_{x\to \pi/3}\frac{1-2cosx}{\pi-3x}$

94. $\displaystyle\lim_{x\to \pi/4}\frac{cosx-senx}{cos2x}$

95. $\displaystyle\lim_{x\to 0}\frac{\sqrt{2}-\sqrt{1+cosx}}{sen^2x}$

96. $\displaystyle\lim_{x\to 1}\frac{cos\frac{\pi}{2}x}{1-\sqrt{x}}$

97. $\displaystyle\lim_{x\to 0}\frac{1-cosx\sqrt{cosx}}{x{2}}$

98. $\displaystyle\lim_{x\to n/2}\frac{1-senx}{(x-\pi/2)^2}$

99. $\displaystyle\lim_{\theta\to 0} \frac{(1-cos\theta)^2}{tan^5\theta-tan^3\theta}$

100. $\displaystyle\lim_{x\to 0} \frac{\sqrt{1+senx}-\sqrt{1-senx}}{tanx}$

101. $\displaystyle\lim_{\theta\to a} \frac{sen\theta-sena}{sen(0/2)-sen(a/2)}$

102. $\displaystyle\lim_{x\to 0}\frac{cos(a+x)-cos(a-x)}{x}$

103. $\displaystyle\lim_{x\to 0}\frac{sen(a+x)-sen(a-x)}{tan(a+x)-tan(a-x)}$

104. $\displaystyle\lim_{x\to \frac{\pi}{6}}\frac{2sen^2x-3senx+1}{2sen^2x+senx-1}$

105. $\displaystyle\lim_{x\to \frac{\pi}{4}}\frac{2tan^2x-tanx-1}{2tan^2x-3tanx+1}$

\newpage

# CONTINUIDAD

1. Probar que la función $f$ es continua en el punto 2.

$f(x)=\left\{
\begin{matrix}
\displaystyle\frac{x^2-4}{x-2}&\text{si}\quad x\ne 2\\
4& \text{si}\quad x=2
\end{matrix}
\right .$


2. Definir $g(0)$ para que la función $g$ sea continua en 0. $g(x)=\frac{\sqrt{x+1}-1}{x}$

3. Probar que la siguiente función es discontinua en el punto 3 y que 3 es el único punto de discontinuidad.

$$
g(x)=\left\{
\begin{matrix}
x^2-2x+2 &\text{si}\quad x <3\\
4& \text{si}\quad x=3\\
-x+8 &\text{si}\quad x >3
\end{matrix}
\right .
$$

En los problemas del 4 al 11, hallar los puntos de discontinuidad de las funciones dadas, indicando el tipo de discontinuidad:

4. $f(x)=\frac{1}{x}$

5. $g(x)=\frac{1}{x+2}$

6. $h(x)=\frac{1}{x^2-4}$

7. $f(x)=\frac{x-1}{x-5}$

8. $g(x)=\frac{x+2}{(x-3)(x+8)}$

9. $h(x)=\frac{x+3}{\sqrt{x-2}}$

10. $f(x)=\frac{x^2-9}{|x-3|}$

11. $g(x)=\frac{|x-1|}{(x-1)^3}$

En los problemas del 12 al 15, graficar la función dada y localizar, mirando el gráfico, los puntos de discontinuidad.

12. 
$f(x)=\left\{
\begin{matrix}
-2&\text{si}& x <3\\
1 &\text{si}& 3\le x<5\\
4 &\text{si}& x \ge 5
\end{matrix}
\right .$


13. 
$g(x)=\left\{
\begin{matrix}
3x+1 &\text{si}& x <-2\\
2x-1 &\text{si}& -2\le x<4\\
\displaystyle-\frac{x}{2}+2 &\text{si}& x \ge 4
\end{matrix}
\right .$


14. $f(x)=\left\{
\begin{matrix}
\displaystyle\frac{x^2}{2}+1&\text{si}& x <2\\
2x-3 &\text{si}& x \ge 2
\end{matrix}
\right .$


15. $g(x)=\left\{
\begin{matrix}
-1 &\text{si}& x \le-2\\
\displaystyle\frac{1}{x+1} &\text{si}& -2 <x<2\\
2x &\text{si}& x \ge 2
\end{matrix}
\right .$


En los problemas del 16 al 19, hallar a y b para que las funciones dadas sean continuas es sus dominios.

16. $g(x)=\left\{
\begin{matrix}
-2 &\text{si}& x <-1\\
ax+b &\text{si}& -1\le x<3\\
2 &\text{si}& x \ge 3
\end{matrix}
\right .$


17. $g(x)=\left\{
\begin{matrix}
-sen^2x &\text{si}& x <\pi/4\\
ax+b &\text{si}& \pi/4\le x\le\pi/3\\
cos^2x &\text{si}& x \ge >/3
\end{matrix}
\right .$


18. $g(x)=\left\{
\begin{matrix}
-2senx &\text{si}& x\le-\pi/2\\
a senx+b &\text{si}& -\pi/2< x<pi/2\\
cosx &\text{si}& x \ge\pi/2
\end{matrix}
\right .$


19. $g(x)=\left\{
\begin{matrix}
a-x^2 sen\frac{\pi}{x}&\text{si}& x\ne 0\\
b,  &\text{si}&  x=0
\end{matrix}
\right .$


En los problemas del 20 al 25, hallar el conjunto de puntos donde la función dada es discontinua.

20. $f(x)=[x+1/2]$

21. $g(x)=[x/4]$

22. $h(x)=1/[x]$

23. $g(x)=[\sqrt{1-x^2}]$

24. $g(x)=1-x+[x]-[1-x]$ 

Sugerencia:
$g(x)=\left\{
\begin{matrix}
1-x+2n,&\text{si}& n<x<n+1\\
n,  &\text{si}&  x=n
\end{matrix}
\right .$


25. $f(x)=\left\{
\begin{matrix}
0, &\text {si x es racional}\\
1, &\text {si x es irracional}
\end{matrix}
\right .$

Sugerencia: En todo intervalo abierto siempre existe un racional y un irracional.

En los problemas del 26 al 28, probar que la ecuación dada una raíz en el intervalo indicado.  Aproximar la raíz con un error menor que 0,1.

26. $x^3+1=3x,\quad en[1,2]$

27. $2x^3-3x^2-12x+2=0,\quad en[-2,-1]$

28. $cosx=x,\quad en[0,1]$

29. Sea $f$ una función con dominio $\mathbb{R}$ tal que:

$$f(x+y)=f(x)f(y),\quad \forall{x}\in\mathbb{R},\quad  \forall\quad y\quad \in\mathbb{R}.$$

Si $f$ es continua en 0, probar que $f$ es continua en todo punto a.   


\newpage

# LIMITES INFINITOS Y ASINTOTAS VERTICALES

1. $f(x)=\frac{1}{x-2}$

2. $g(x)=\frac{1}{|x-2|}$

3. $h(x)=\frac{1}{(x+1)^2}$

4. $f(x)=\frac{x}{x-4}$

5. $g(x)=\frac{x+1}{x-5}$

6. $h(x)=\frac{1}{x(x+2)}$

7. $f(x)=\frac{x}{x^2-2x+3}$

8. $g(x)=\frac{x^2+4}{x^2-4}$

9. $h(x)=x-\frac{1}{x}$

En los problemas del 10 al 28 calcular el limite indicado.

10. $\displaystyle\lim_{x\to 0^+}[x]/x$

11. $\displaystyle\lim_{x\to 0^-}[x]/x$

12. $\displaystyle\lim_{x\to (\pi/2)^-}secx$

13. $\displaystyle\lim_{x\to (\pi/2)^+}secx$

14. $\displaystyle\lim_{x\to (-3\pi/2)^+}secx$

15. $\displaystyle\lim_{x\to 1^+} \left[\frac{x-1}{1-\sqrt{2x-x^2}}\right]$

16. $\displaystyle\lim_{x\to 2^+} \left[\frac{x-2}{\sqrt{4x-x^2}-2}\right]$

17. $\displaystyle\lim_{x\to 2^+}\frac{\sqrt{x^2-4}}{x-2}$

18. $\displaystyle\lim_{x\to 0^+} \left[\frac{1}{x}-\frac{1}{x^2}\right]$

19. $\displaystyle\lim_{x\to 0^+} \left[\frac{1}{x^2-4}-\frac{1}{x-2}\right]$

20. $\displaystyle\lim_{x\to 1^-}([x^2]-1)/(x^2-1)$

21. $\displaystyle\lim_{y\to 1+} \left[\frac{1}{y-1}-\frac{3}{y^3-1}\right]$

22. $\displaystyle\lim_{y\to 0}\frac{1}{y\sqrt{y+1}}-\frac{1}{y}$

23.  $\displaystyle\lim_{x\to 0^-} \left[\frac{1}{x}-\frac{1}{|x|}\right]$

24. $\displaystyle\lim_{x\to 0^+}\left[\frac{1}{x}-\frac{1}{|x|}\right]$

25. $\displaystyle\lim_{x\to 0^+}x\quad cosec(x2)$

26. $\displaystyle\lim_{x\to 0^+} \left[\frac{1}{x}-\frac{cos^2x}{x}\right]$

27. $\displaystyle\lim_{x\to (\pi/2)}\left[\frac{tanx}{\sqrt[3]{(1-cosx)^2}}\right]$

28. $\displaystyle\lim_{x\to 0^+} \left[\frac{1-cosx}{tan^3-sen^3x}\right]$

En los problemas del 29 al 32, hallar las asintotas verticales a la gráfica de la función dada.

29. $y=\frac{\sqrt{1+x^2}}{x}$

30. $y=\frac{x}{4x^2-1}$

31. $y=\frac{x}{\sqrt{x^2-1}}$

32. $y=\frac{x^2}{\sqrt{x^2-1}}$

33. Demostrar que las rectas $x=(2n+1)\frac{\pi}{2}$, donde n es un entero, son asíntotas verticales de la gráfica de $y=tanx$.


# LIMITES EN EL INFINITO Y ASINTOTAS HORIZONTALES

1. $f(x)=\frac{1}{x^2}$

2. $f(x)=\frac{-1}{x^3}$

3. $f(x)=\frac{x+2}{x-3}$

4. $f(x)=\frac{x^2}{x+2}$

5. $f(x)=\frac{x^3-8}{2x^3-3x^2+1}$

6. $f(x)=x^5-4x^4$

7. $f(x)=-2x^6+5x^5$

8. $f(x)=\frac{x+1}{x}$

9. $f(x)=x^2-\frac{1}{x}$

En los problemas del 10 al 31 calcular el limite indicado.

10. $\displaystyle\lim_{x\to +\infty}[x+\sqrt{x}]$

11. $\displaystyle\lim_{x\to +\infty}[x-\sqrt{x}]$

12. $\displaystyle\lim_{x\to +\infty}\frac{\sqrt{x}+1}{\sqrt{x+1}}$

13. $\displaystyle\lim_{x\to +\infty}\frac{\sqrt{x}+1}{x+1}$

14. $\displaystyle\lim_{x\to +\infty}\frac{x}{\sqrt{x-1}}$

15. $\displaystyle\lim_{x\to +\infty}\frac{\sqrt[3]{-8x^3+x+1}}{x-1}$

16. $\displaystyle\lim_{x\to +\infty}[\sqrt{x+1}-\sqrt{x}]$

17. $\displaystyle\lim_{x\to +\infty}[\sqrt{x^2+2x}-{x}]$

18. $\displaystyle\lim_{x\to +\infty}[\sqrt{x^2+5}-x$

19. $\displaystyle\lim_{x\to +\infty}[x+\sqrt[3]{1-x^3}]$

20. $\displaystyle\lim_{x\to +\infty}\frac{2x}{\sqrt{x^2+1}}$

21. $\displaystyle\lim_{x\to -\infty}\frac{2x}{\sqrt{x^2+1}}$

22. $\displaystyle\lim_{x\to +\infty} \frac{\sqrt{x}}{\sqrt{4x++\sqrt{x}+{\sqrt{x}}}}$

23. $\displaystyle\lim_{x\to +\infty}x^{-1/2}senx$

24. $\displaystyle\lim_{x\to +\infty} \left(\frac{1}{x}+\frac{\pi}{6}\right)$

25. $\displaystyle\lim_{x\to +\infty}[sen\sqrt{x+2}-sen\sqrt{x}]$

26. $\displaystyle\lim_{x\to +\infty}\frac{c^{2x}}{e^{2x}+1}$

27. $\displaystyle\lim_{x\to +\infty}\frac{e^{3x}-e^{3x}}{e^{3x}+e^{3x}}$

28. $\displaystyle\lim_{x\to +\infty}\frac{10^x}{10^x+1}$

29. $\displaystyle\lim_{x\to +\infty}\left(2^{-06x}+\frac{1}{x}\right)$

30. $\displaystyle\lim_{x\to +\infty}\left[1+e^{-x^2}\right]$

31. $\displaystyle\lim_{x\to +\infty}[In(2+x)-In(1+x)]$

32. Sea la función racional $f(x)=\frac{a_nx^n...+a_1x+a_0}{b_mxm+...+b_1x+b_0}. a_a\ne0\quad y\quad b_m\ne0$ Probar que:

a. $n=m\Rightarrow\quad \displaystyle\lim_{x\to \pm \infty}f(x)=\frac{a_n}{b_m}$

b. $n<m\Rightarrow\quad \displaystyle\lim_{x\to \pm \infty}f(x)=0$

c. $n>m\Rightarrow\quad \displaystyle\lim_{x\to \pm \infty}f(x)= 
\left\{
\begin{matrix}
+\infty, & si & \frac{a_n}{b_m} & >0\\
-\infty, & si & \frac{a_n}{b_m} & <0
\end{matrix}
\right .$

33. Dar una definición rigurosa de:

a. $\displaystyle\lim_{x\to +\infty}f(x)=+\infty$

b. $\displaystyle\lim_{x\to -\infty}f(x)=+\infty$

c. $\displaystyle\lim_{x\to +\infty}f(x)=-\infty$

d. $\displaystyle\lim_{x\to -\infty}f(x)=-\infty$

34. Probar que todo polinomio de grado impar tiene una raíz (real).  
Sugerencia: Hallar los límites en $+\infty$ y en $-\infty$.

En los problemas del 35 al 41 hallar las asintotas horizontales del gráfico de la función dada.

35. $f(x)=\frac{1}{x-1}$

36. $g(x)=\frac{1}{x(x+2)}$

37. $g(x)=\frac{x}{4x^2-1}$

38. $f(x)=\frac{2x}{\sqrt{x^2+1}}$

39. $g(x)=\frac{x}{\sqrt{x^2-1}}$

40. $h(x)=\frac{x^2}{\sqrt{x^2-1}}$

41. $f(x)=\frac{senx}{x}$

En los problemas del 42 al 44 hallar las asíntotas verticales y horizontales del gráfico de la ecuación dada.

42. $2x^2+yx^2=16y$

43. $(y^2-4)(x-1)=8$

44. $x^2y^2=2y^2+x^2+1$


# LOS LIMITES Y EL NUMERO e

1. $\displaystyle\lim_{x\to 0}\frac{In(1+ax)}{x}$

2. $\displaystyle\lim_{x\to 0}\frac{In(a+x)-Ina}{x}$

3. $\displaystyle\lim_{x\to e}\frac{Inx-1}{x-e}$

4. $\displaystyle\lim_{x\to 0}\frac{ex-e}{x-1}$

5. $\displaystyle\lim_{x\to 0}\frac{e^{ax}-e{bx}}{x}$

6. $\displaystyle\lim_{x\to +\infty}x(e^{1/x}-1)$


# ASINTOTAS OBLICUAS

1. $y=\frac{x^2}{x-1}$

2. $y=\frac{x^3}{x^2-1}$

3. $y=\frac{x^3}{2(x^2+1)^2}$

4. $y=\frac{2x^4+x^2+x}{x^3-x^2+2}$

5. $y=\sqrt{x^2-1}$

6. $y=\frac{x^2+1}{\sqrt{x^2-1}}$

7. $f(x)=x-2+\frac{x^2}{\sqrt{x^2+3}}$

8. $f(x)=x^{2/3}(6-x)^{1/3}$


