---
title: "Ejercicios de Funciones"
subtitle: "Cálculo"
author: "http://synergy.vision/"
output:
  pdf_document:
      toc: yes
      toc_depth: 4
      includes:
        in_header: ./preambulo.tex
  html_document: default
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newpage

# Ejercicio 1

Hallar el dominio y el rango de las funciones dadas:

a) $$f(x) =\sqrt{X - 9} $$

b) $$g(x) =\displaystyle\frac{\sqrt{16-X^2}}{3}$$

c) $$h(x) =\displaystyle\frac{\sqrt{X^2-4}}{2}$$

d) $$u(x) = \sqrt[3]{X-2}$$

e) $$y = \frac{1}{\sqrt{x^2-4-2}}$$

f) $$y = \sqrt{4-\frac{1}{x}}$$


# Ejercicio 2

Un hotel tiene 40 habitaciones. El gerente sabe que cuando el precio por
habitación es de Bs. 30.000 todas las habitaciones son alquiladas, pero por cada 5.000 bolívares de aumento una habitación se desocupa. Si el precio de mantenimiento de una habitación ocupada es de Bs. 4.000. Expresar la ganancia del hotel como función del número x de habitaciones alquiladas.

# Ejercicio 3

Cuando la producción diaria no sobrepasa de 1.000 unidades de cierto artículo, se tiene una utilidad de Bs. 4.000 por artículo; pero si el número de artículos producidos excede los 1.000, la utilidad, para los excedentes, disminuye en Bs. 10 por cada artículo que excede los 1.000. Expresar la utilidad diaria del productor como función del número x de artículos producidos.

# Ejercicio 4

Una finca está sembrada de mangos a razón de 80 plantas por hectárea. Cada
planta produce un promedio de 960 mangos. Por cada planta adicional que se
siembre, el promedio de producción por planta se reduce en 10 mangos. Expresar la producción p(x) de mangos por hectárea como función del número x de plantas de mango sembradas por hectárea.

# Ejercicio 5

Usando la gráfica de $f(x)=x^3$, bosquejar los gráficos de:

a) $y=x^3-3$

b) $y={(x-1)}^3$

c) $y=-x^3+1$

d) $y=-(x-1)^3+1$

# Ejercicio 6

Utilizando la gráfica de la función y = sen x y las técnicas de traslación y reflexión, graficar la función 

$y=1-sen(x-\frac{\pi}{2})$

# Ejercicio 7

En los siguientes problemas hallar f + g, f-g, fg y $\frac{f}{g}$ con sus respectivos dominios:

a) $f(x)=\frac{1}{1-x},\quad g(x)=\sqrt{2-x}$

b) $f(x)=\sqrt{16-x^2}, \quad g(x)=\sqrt{x^2-4}$

c) $f(x)=\frac{1}{\sqrt4-x^2}, \quad g(x)=\sqrt[3]{x}$

# Ejercicio 8

En los siguiente problemas hallar f ó g, g ó f, f ó f y g ó g, con sus respectivos dominios:

a) $f(x)=x^2-1, \quad g(x)=\sqrt{x}$

b) $f(x)=\frac{1}{1-x}, \quad g(x)=\sqrt[3]{x}$

\newpage

# INTERES SIMPLE

Un capital colocado a interés simple permanece constante durante toda la
operación . El interés ganado no genera interés. Es fácil deducir que: Un capital **P** colocado durante t años a **interés simple** y a **una tasa anual** de **100r%** produce un monto de:

| M(t) = P(1 + rt)      (1) |
|---------------------------|

# INTERES COMPUESTO

En UD capital a **interés compuesto**, el interés ganado en cada periodo es agregado al capital, para ganar interés en el próximo período; o sea, el interés se capitaliza o se compone después de cada periodo. Este periodo puede ser de 1 año (anual), 6 meses (semestral: 2 periodos al año), 3 meses (trimestral: 4 periodos al año), 1 mes (mensual: 12 periodos al año), etc.

Además de la **tasa anual**, se tiene la **tasa periódica**, que es el tanto por ciento por período de capitalización. Si el año está dividido en n períodos iguales, entonces

$$\text{Tasa periódica}=\frac{Tasa\quad anual}{n}$$

Así, si la tasa anual es de 24% y el periodo de capitalización es de 3 meses (4 períodos al año) entonces la tasa periódica es de $\frac{24}{4}\%=6\%$

Un capital **P** que se coloca durante **t años** a una tasa de **100r%** anual que se capitaliza (se compone) n veces al año produce un monto:

| M(t) = P(1 + $\frac{r}{n})^{nt}$     (2) |
|--------------------------------------|


# INTERES COMPUESTO CONTINUO

Cuando el número n de periodos de capitalización crece ilimitadamente; es decir, cuando $n\to+\infty$  , se obtiene el interés compuesto continuo. Aquí, la capitalización es instantánea y se la denomina **capitalización continua.**
Un **capital P** colocado durante t años a un interés anual de 100r % que se capitaliza continua mente , produce un monto de:

| M(t) = Pe$^{rt}$       (3) |
|--------------------------|

Está fórmula se obtiene de la anterior tomando límite.

\newpage

# Ejercicio 9

**(Utilidades)**. Las utilidades de una compañía crecen exponencialmen te: $f(t) = Ae^{kt}$. En 1.995 éstas fueron de 3 millones de dólares y en el 2.000 fueron de 4,5 millones. ¿Cuáles son las utilidades en 2.005?

# Ejercicio 10

**(Producto Nacional Bruto)**. El producto nacional bruto (P.N.B.) de cierto país, t años después de 1.995, es de f(t) millones de dólares, donde
$$f(t)=P(10)^{kt},\text{P y k son constantes}$$
Si en 1.995 el P.N.B. fue de 8.000 millones de dólares y en el 2,000 fue de 16.000 millones de dólares. ¿Cuál será el P.N.B. en el año 2.010?

# Ejercicio 11

**(Venta de libros)**. Una editorial, estudiando el mercado, ha descubierto que si se distribuyen x miles de ejemplares gratuitos de un texto, la venta de dicho texto será, aproximadamente,

$$V(x)=30-18^{0,3x}\text{miles de ejemplares}$$

a. ¿Cuántos textos se venderán si no se handistribuido ejemplares gratuitos?

b. ¿Cuántos se venderán si se han regalado 800 ejemplares?

# Ejercicio 12

**(Cálculo del monto)**. Se deposita un capital de 12 millones de dólares en un banco que paga 14% anual de interés compuesto continuo ¿En cuántos años se tendrá un monto de 21 millones?

# Ejercicio 13

**(Venta de un texto)**. Un nuevo texto de cálculo saldrá al mercado. Se estima que si se obsequian x miles de ejemplares a los profesores, en el primer año se venderán $f(x) =12 - 5e^{-O,2x}$ miles de ejemplares. ¿Cuántos textos deben obsequiarse si se quiere una venta en el primer año de 9.000 ejemplares?

# Ejercicio 14

**(Producto Nacional Bruto)**. El producto nacional bruto (P.N.B.) de cierto paÍs esta creciendo exponencialmente. En 1.995 fue 60.000 millones y en 2.000 fue de 70.000 millones.¿Cuál es el PNB en el 2.005?

# Ejercicio 15

**(Cálculo del monto)**. Se pide prestado a un banco Bs. 7.500.000 para ser pagado en dos años, ganando interés de 28% anual. Hallar la cantidad de dinero que deberá devolverse al banco si

a) El interés es simple. asdfasdf

b) El interés se compone anualmente.

c) El interés se compone trimestralmente.

d) El interés se compone mensualmente.

e) Elinterés se compone continuamente.

# Ejercicio 16

**(Cálculo del principal)**. ¿Qué capital produce un monto de \$2.500.000 al final de 5 años si la lasa es de 16 % anual que se compone:

a) Trimestralmente? 

b) Continuamente?

# Ejercicio 17

**(Cálculo del monto)**. En el año 1.626 el holandés Piter Minuit compró a los nativos la "isla" de Manhattan (Nueva York), por 24 dólares. Suponga que los nativos depositaron estos 24 dólares en un banco, ganando una tasa anual de 5 % que se compone continuamente. ¿Cuál es monto en el año 2.000?

# Ejercicio 18

El gerente de un mercado de pulgas de fin de semana sabe por experiencia que si cobra dólares por un espacio alquilado en el mercado, entonces la cantidad de espacios que puede alquilar viene dada por la ecuación

a) Dibuje un gráfico de esta función lineal. (Recuerde que el cargo por alquiler por espacio y el número de espacios alquilados no pueden ser cantidades negativas).

b) ¿Qué representan la pendiente, el intercepto y el intercepto de la gráfica?

# Ejercicio 19

El gerente de una fábrica de muebles descubre que cuesta \$2200 para fabricar 100 sillas en un día y \$4800 para producir 300 sillas en un día

a) Exprese el costo en función de la cantidad de sillas producidas, suponiendo que sea lineal. Luego dibuja el gráfico.

b) ¿Cuál es la pendiente del gráfico y qué representa?

c) ¿Cuál es la intersección y del gráfico y qué representa?

# Ejercicio 20

El costo mensual de conducir un automóvil depende de la cantidad de millas recorridas. Lynn descubrió que en mayo le costó \$380 manejar 480 millas y en junio le costó \$460 manejar 800 millas.

a) Exprese el costo mensual como una función de la distancia impulsada asumiendo que una relación lineal da un modelo adecuado.

b) Use la parte (a) para predecir el costo de conducir 1500 millas por mes.

c) Dibuje el gráfico de la función lineal. ¿Qué representa la pendiente?

d) ¿Qué representa el C-interceptar?

e) ¿Por qué una función lineal proporciona un modelo adecuado en esta situación?

# Ejercicio 21

Si invierte $x$ dólares al 4% de interés compuesto anualmente, entonces el monto $A(x)$ de la inversión después de un año es $A(x)=1.04x$. Encontrar $A\circ A, A\circ A\circ A,$y $A\circ A\circ A\circ A$. ¿Qué
representan estas composiciones? Encuentre una fórmula para la composición de n de copias de $A$.

# Ejercicio 22

arifas de servicios públicos Westside Energy cobra a sus clientes de electricidad una tarifa base de \$6.00 por mes, más $10\cancel{c}$ por kilovatio hora (kWh) por los primeros 300 kWh usados y $6\cancel{c}$ por kWh para todo uso superior a 300 kWh. Supongamos que un cliente usa x kWh de electricidad en un mes.

a) Exprese el costo mensual E como una función definida por partes de $x$.

b) Grafica la función $E$ para $0\le x\le 600.$

# Ejercicio 23

**Ingresos, costos y ganancias** Una imprenta hace adhesivos para las campañas electorales. Si se piden $x$ etiquetas $(dónde x<10,000)$, entonces el precio por etiquetas para parachoques es en dólares $0.15-0.000002x$, y el costo total de producir la orden es $0.095x-0.0000005x^2$ dólares.

# Ejercicio 24

Use el hecho de que

$$\text{ingresos} =\text{precio por artículo}\times\text{cantidad de artículos vendidos}$$

para expresar $R(x)$, los ingresos de una orden de $x$ etiquetas, como
producto de dos funciones de $x$.


# Ejercicio 25

Use el hecho de que

$$\text{lucro}=\text{ingresos}-\text{costos}$$

para expresar, la ganancia en un orden de $x$ etiquetas, como una diferencia de dos funciones de $x$.

# Ejercicio 26

Para sus servicios, un investigador privado requiere una tarifa de retención de \$500 más \$80 por hora. Sea $x$ el número de horas que el investigador pasa trabajando en un caso

a) Encuentre una función $f$ que modele la tarifa del investigador como una función de $x$.

b) Encuentra $f^-1$. ¿Qué representa $f^1$?

c) Encuentre $f^1$(1220). ¿Qué representa tu respuesta?

# Ejercicio 27

**Tipos de cambio** El valor relativo de las monedas fluctúa todos los días. Cuando se escribió este problema, un dólar canadiense valía 1.0573 dólares estadounidenses.

a) Encuentre una función $f$ que proporcione el valor $f(x)$ en dólares de EE. UU. de $x$ dólares canadienses.

b) Encuentra $f^1$. ¿Qué representa $f^1$?

c) ¿Cuánto dinero canadiense valdría \$12,250 en moneda de EE. UU.?

# Ejercicio 28

**En comeTax** En un determinado país, el impuesto sobre los ingresos inferiores o iguales a 20,000€ es del 10%. Para los ingresos que superan los 20.000 €, el impuesto es de 2000 € más el 20% del importe superior a 20.000 €.

a) Encuentre una función $f$ que dé el impuesto a la renta sobre un ingreso $x$. Exprese $f$ como una función definida por partes.

b) Encuentra $f^{-1}$. ¿Qué representa $f^{-1}$?

c) ¿Cuánto ingreso requeriría pagar un impuesto de € 10,000?

# Ejercicio 29

**Descuentos múltiples** Un concesionario de automóviles anuncia un descuento del 15% en todos sus automóviles nuevos. Además, el fabricante ofrece un descuento de \$1000 en la compra de un automóvil nuevo. Deje $x$ representar el precio de etiqueta del coche.

a) Supongamos que solo se aplica el descuento del 15%. Encuentre una función $f$ que modele el precio de compra del automóvil en función del precio de etiqueta $x$.

b) Supongamos que solo se aplica el descuento de \$1000. Encuentre una función $g$ que modele el precio de compra del automóvil en función del precio de etiqueta $x$.

c) Encuentre una fórmula para $H=f\circ{g}$.

d) Encuentre $H^{-1}$. ¿Qué representa $H^{-1}$?

e) Encuentre $H^{-1}$(13,000). ¿Qué representa tu respuesta?

# Ejercicio 30

**Pizza Costo** Marcello's Pizza cobra un precio base de \$7 por una pizza grande más \$2 por cada cobertura. Por lo tanto, si pide una pizza grande con coberturas $x$, la función otorga el precio de su pizza $f(x)=7+2x$. Encuentra $f^{-1}$. ¿Qué representa la función $f^{-1}$?

# Ejercicio 31

Un editor estima que el costo $C(x)$ de imprimir una corrida de $x$ copias de cierto libro de texto de matemáticas está dado por la función $C(x)=5000+30x-0.001x^2.$

a) Encuentre $C(1000)$ y $C(10,000)$.

b) ¿Qué representan sus respuestas en la parte (a)?

c) Encuentra $C(0)$. ¿Qué representa este número?

# Ejercicio 32

Reyna trabaja como vendedora en la división de electrónica de una tienda por departamentos. Ella gana un salario base semanal más una comisión basada en el precio minorista de los productos que ha vendido. Si ella vende $x$ dólares en bienes en una semana, sus ganancias para esa semana están dadas por la función $E(x)=400+0.03x.$

a) Encuentre $E(2000)$ y $E(15,000).$

b) ¿Qué representan sus respuestas en la parte a?

c) Encuentre $E(0).$ ¿Qué representa este número?

d) De la fórmula para $E$, determine qué porcentaje gana Reyna en los bienes que vende.

# Ejercicio 33

Ella está ahorrando para su jubilación al hacer depósitos regulares en un plan 401(k). A medida que aumenta su salario, descubre que puede depositar cantidades crecientes cada año. Entre 1995 y 2008, el monto anual (en dólares) que depositó fue dado por la función $D(t)=3500+15t^2$, donde $t$ representa el año del depósito medido desde el inicio del plan (de modo que 1995 corresponde a $t=0$ y 1996 corresponde a $t=1,$ y así sucesivamente).

a) Encuentra $D(0)$ y $D(15)$. ¿Qué representan estos valores?

b) Suponiendo que sus depósitos sigan siendo modelados por la función D, ¿en qué año depositará \$17,000?

c) Encuentre la tasa promedio de cambio de $D$ entre $t=0$ y $t=15.$ ¿Qué representa este número?

# Ejercicio 34

La ganancia $P$ (en dólares) generada al vender $x$ unidades de un determinado producto está dada por

$$P(x)=-1500+12x-0,0004x^2$$

¿Cuál es el beneficio máximo y cuántas unidades se deben vender para generarlo?

# Ejercicio 35

Encuentre los valores máximos y mínimos locales de la función y los valores de $x$ a los que ocurren. Establezca cada respuesta correcta en dos decimales.

# Ejercicio 36

Si $f(x)=1+x^2-\quad \text{y}\quad g(x)=\sqrt{x-1},\text{encuentra el siguiente}$

a) $f\circ{g}$

b) $g\circ{f}$

c) $(f\circ{g})(2)$

d) $(f\circ{f})(2)$

e) $f\circ{g}\circ{f}$

f) $g\circ{f}\circ{g}$

# Ejercicio 37

**FUNCIÓN DE COSTOS** Los costos fijos por día para una tienda de donuts son de \$300, y los costos variables son de \$1.75 por cada docena de donas producidas. Si se producen diariamente $x$ docenas de donuts, exprese el costo diario $C(x)$ como una función de $x.$

# Ejercicio 38

**FUNCIÓN DE COSTOS** Un fabricante de reproductores de MP3 ha fijado un costo diario de 15.700 yuanes chinos, y cuesta 178 yuanes producir un solo reproductor de MP3. Si el fabricante produce $x$ reproductores diariamente, exprese el costo diario $C$ en yuan en función de $x.$

# Ejercicio 39

**COSTO DEL TELÉFONO CELULAR** Dado que Don generalmente toma prestado el teléfono celular de su compañero de cuarto para llamadas de larga distancia, elige un plan económico para su propio teléfono con un cargo de acceso mensual y un cargo variable por cada hora de llamadas utilizada. La función

$$C(h)=17+2.40h$$

se usa para calcular la factura mensual de Don, donde $C$ es el costo en dólares y $h$ es horas de tiempo de uso. Traduzca esta ecuación en una declaración verbal que podría usar para explicar el cargo mensual de Don.

# Ejercicio 40

**COSTO DE INTERNET DE ALTA VELOCIDAD** Una universidad ofrece Internet de alta velocidad en dormitorios. La tarifa de acceso mensual en dólares se calcula utilizando la función

$$A(m)=15+0.02m$$

donde $m$ es la cantidad de minutos pasados en línea. Traduzca esta ecuación en una declaración verbal que pueda usarse para explicar los cargos mensuales a un estudiante de primer año entrante.

# Ejercicio 41

**ALQUILER DE AUTOMÓVILES** Utilice los datos de la siguiente tabla  para construir un modelo definido por partes para el cargo de alquiler diario para un automóvil compacto que se conduce x millas.

| Tipo de Vehículo | Cargo diario | Millas incluidas | Cargo por millaje |
|:----------------:|:------------:|:----------------:|:-----------------:|
| Compacto | \$32.00 | 100/día | \$0.16/milla |
| Tamaño medio | \$41.00 | 200/día | \$0.18/milla |

# Ejercicio 42

**ALQUILER DE AUTOMÓVILES** Use los datos de la Tabla anterior (ejercicio 41) para construir un modelo definido por partes para el cargo de alquiler diario para un automóvil de tamaño medio que se conduce $x$ millas.

# Ejercicio 43

**COMISIONES DE VENTAS** Un sitio web de alto volumen paga a los vendedores para solicitar anuncios de colocación en su sitio. El personal de ventas gana \$200 por semana en salario y una comisión del 4% en todas las ventas de \$3,000 por semana. Además, si las ventas semanales son de \$8,000 o más, el vendedor recibe un bono de \$100. Encuentre una definición por partes para las ganancias semanales $E$ (en dólares) en términos de las ventas semanales $x$ (en dólares). Grafica esta función y encuentra los valores de $x$ en los que la función es discontinua. Encuentre las ganancias semanales para ventas de \$5,750 y de \$9,200.

# Ejercicio 44

**CARGOS DE SERVICIO** Los fines de semana y feriados, un servicio de reparación de plomería de emergencia cobra \$2.00 por minuto durante los primeros 30 minutos de una llamada de servicio y \$1.00 por minuto por cada minuto adicional. Exprese el cargo de servicio total $S$ (en dólares) como una función definida por partes de la duración de una llamada de servicio $x$ (en minutos). Grafica esta función y encuentra los valores de $x$ en los que la función es discontinua. Encuentre el cargo por una llamada de servicio de 25 minutos y por una llamada de servicio de 45 minutos.

# Ejercicio 45

**CARGOS TELEFÓNICOS** Las llamadas a 900 números se cargan a la persona que llama. Una línea de 900 números para consejos sobre juegos de fútbol americano universitario cobra \$4 por el primer minuto de la llamada y \$2 por cada minuto adicional (o fracción). Deje que $C$ sea el cargo por una llamada que dure $x$ minutos.

a) Escribe una definición por partes de $C$ para $0<x\le6$, y dibuja el
gráfico de $C.$

b) ¿Se puede usar la función $f$ definida por $f(x)=4+2[[x]]$ para calcular los cargos por todos $x, 0<x\le6$? Justifica tu respuesta.

# Ejercicio 46

**IMPUESTO SOBRE LA RENTA ESTATAL** Los impuestos estatales a la renta de Connecticut para una persona que presenta una sola declaración son del 3% por los primeros \$10,000 de ingresos gravables y del 5% de los ingresos imponibles que superen los \$10,000. Encuentre una función definida por partes para los impuestos adeudados por un solo declarante con un ingreso de $x$ dólares y grafica esta función.

# Ejercicio 47

**IMPUESTO SOBRE LA RENTA DEL ESTADO** Los impuestos estatales sobre la renta de Connecticut para un individuo que presenta una declaración del jefe de familia son del 3% por los primeros \$16,000 del ingreso gravable y del 5% del ingreso gravable que excede los \$16,000. Encuentre una función definida por partes para los impuestos adeudados por un declarante del jefe de familia con un ingreso de $x$ dólares y grafica esta función.

# Ejercicio 48

**IMPUESTO SOBRE LA RENTA ESTATAL** Use el cronograma de la siguiente tabla para construir un modelo definido por partes para los impuestos adeudados para un contribuyente único con un ingreso imponible de $x$ dólares. Encuentre el impuesto sobre los siguientes ingresos: \$10,000, \$30,000, \$100,000.

|  Estado | Impuestos sobre los ingresos imponibles | Impuesto sobre los ingresos no imponibles |   Impuestos   | Cantidad por encima de los impuestos |
|:-------:|:---------------------------------------:|:-----------------------------------------:|:-------------:|:------------------------------------:|
| Soltera |                   \$0                   |                  \$19,890                  |     5.35%     |                  \$0                 |
|         |                  19,890                 |                   65,330                  | \$1,064+7.05% |                19,890                |
|         |                  65,330                 |                    ...                    |  4,268+7.85%  |                65,330                |
|  Casada |                    0                    |                   29,070                  |     5.35%     |                   0                  |
|         |                  29,070                 |                  115,510                  |  1,555+7.05%  |                29,070                |
|         |                 115,510                 |                   . . .                   |  7,649+7.85%  |                115,510               |

# Ejercicio 49

**IMPUESTO SOBRE LA RENTA ESTATAL** Use el cronograma de la Tabla anterior (ejercicio 48) para construir un modelo definido por partes para los impuestos adeudados para un contribuyente casado con un ingreso tributable de $x$ dólares. Encuentre el impuesto sobre los siguientes ingresos: \$20,000, \$60,000, \$200,000.

