---
title: "Derivadas"
subtitle: "Cálculo"
author: "http://synergy.vision/"
output:
  pdf_document:
      toc: yes
      toc_depth: 4
      includes:
        in_header: ./preambulo.tex
  html_document: default
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newpage

# LA DERIVADA

En los problemas del 1 al 9, hallar la derivada de la función en el punto a indicado.

1. $f(x)=2\quad en\quad a=1$

2. $g(x)=x\quad en\quad a=3$

3. $h(x)=3x\quad en\quad a=2$

4. $f(x)=4x-1\quad en\quad a=2$

5. $g(x)=2x^2-5\quad en\quad a=-1$

6. $h(x)=\frac{3}{x}\quad en\quad=-2$

7. $f(x)=3x^2-5\quad en\quad a=-1$

8. $g(x)=x+\frac{1}{x}\quad en\quad a=2$

9. $h(x)=x^3+2\quad en\quad a=-1$

10. Probar que la siguiente función es diferenciable en 0: 
$$
f(x)=
\left\{
\begin{matrix}
x^2 & si & x\le0\\
0 & si & x>0
\end{matrix}
\right .
$$

11. Probar que la siguiente función no es diferenciable en 0:

$$
f(x)=
\left\{
\begin{matrix}
1+x & si & x\le0\\
1-x & si & x>0
\end{matrix}
\right .
$$

12. Hallar los valores de a y b para que sea diferenciable en 1:

$$
f(x)=
\left\{
\begin{matrix}
ax+b & si & x<1\\
\sqrt[3]{x} & si & x\ge 1
\end{matrix}
\right .
$$


En los problemas del 13 al 21, hallar la derivada de la función indicada.

13. $f(x)=2$

14. $g(x)=x$

15. $h(x)=3x$

16. $f(x)=4x-1$

17. $g(x)=2x^2-5$

18. $h(x)=\frac{3}{x}$

19. $f(x)=3x^2-5$

20. $g(x)=x+\frac{1}{x}$

21. $h(x)=x^3+2$

22. Dada la función $f(x)=x^3+x^2$

a. Hallar la pendiente de la recta tangente al gráfico de f en el punto donde $x=1.$

b. Hallar la recta tangente al gráfico de f en el punto donde $x=1.$

c. Hallar la recta normal al gráfico de f en el punto donde $x=1.$

23. Dada la función $g(x)=\sqrt{x-3}$

a. Hallar la pendiente de la recta tangente al gráfico de g en el punto donde $x=12$

b. Hallar la recta tangente al gráfico de g en el punto donde $x=12.$

c. Hallar la recta normal al gráfico de g en el punto donde $x=12.$

24. Dada la función $h(x)=\frac{1}{2}x^2-x+7$

a. Hallar su función derivada.

b. ¿En qué punto del gráfico de h la tangente es paralela a la recta $y=3x+6?.$

c. Hallar la recta tangente al gráfico de h en el punto encontrado en la parte b.

25. Dada la función $f(x)=\sqrt{2x+1}$

a. Hallar la función derivada de f.

b. Una tangente al gráfico de f tiene por pendiente 1/2.  Hallar una ecuación de esta tangente.

\newpage

# TÉCNICAS BASICAS DE DERIVACIÓN

En los problemas del 1 al 38, hallar la derivada de la función indicada. Las letas a,b,c y d son constantes.

1. $y=4x^2-6x+1$

2. $y=1-\frac{x}{3}+\frac{x^6}{6}$

3. $y=0,5x^4-0,3x^2+2,5x$

4. $u=y^{10}-\frac{3y^8}{4}+0,4y^3+0,1$

5. $s=2t^{-5}+\frac{t^3}{3}-0,3t^{-2}.$

6. $z=\frac{1}{3y}-\frac{3}{y^2}+2$

7. $f(x)=3x^{5/6}-4x^{-2/3}-10$

8. $g(x)=ax^5-bx^{-4}+cx^{3/2}+d$

9. $y=-\frac{2x^6}{3a}$

10. $z=\frac{x^3}{a+b}+\frac{x^5}{a-b}-x$

11. $z=\frac{t^3-bt^2-3}{6}$

12. $y=4\sqrt{x-}\frac{3}{2x^2}+\sqrt{3}$

13. $z=\sqrt[3]t-\frac{1}{\sqrt[3]t}$

14. $u=\frac{\sqrt3}{2\sqrt x}-\frac{5}{3\sqrt[3]{x^2}}+\sqrt[3]3$

15. $y=(5x^4-4x^5)(3x^2+2x^3)$

16. $y=x^3e^x$

17. $y=\sqrt{x}e^x$

18. $y=x^e+e^x$

19. $y=(x-1)(x-2)(x-3)$

20. $y=\frac{1}{3}(2x^3-1)(3x^2-2)(6x-5)$

21. $z=\sqrt{t}(t^4-1)(t^6-2)$

22. $y=(\sqrt{x-1})(\sqrt{x}+1)$

23. $u=2\sqrt{x}(x^2-\sqrt{x}+\sqrt{5})$

24. $y=(\sqrt{x}-3)\left(\frac{2}{x}-1\right)$

25. $y=\frac{3}{x-9}$

26. $y=\frac{x}{x-8}$

27. $y=\frac{x+3}{x-3}$

28. $z=\frac{t}{t^2+1}$

29. $u=\frac{2t^3+1}{t-1}$

30. $y=\frac{x^3-2x}{x^2+x+1}$

31. $y=\frac{ax^2+bx+c}{x}$

32. $y=\frac{ax^2+bx+c}{\sqrt{}x}$

33. $y=\frac{ax^2+b}{\sqrt{a^2+b^2}}$

34. $y=\frac{x^2+1}{x^2-1}-(x-1)(x^2-1)$

35. $y=\frac{1}{(x-1)(x-3)}$

36. $y=\frac{1-\sqrt{x}}{1+2\sqrt{x}}$

37. $y=\frac{1-\sqrt[3]{x}}{1+3\sqrt[3]{x}}$

38. $y=\frac{e^x-1}{e^x+1}$

En los problemas del 39 al 42, hallar la recta tangente al gráfico de la función en el punto especificado.

39. $y=x^4-3x^2+x-2, (1,-3)$

40. $y=x^2(x-5), (2,-12)$

41. $f(x)=\frac{x^2-2}{x^2-3},(-1,\frac{1}{2})$

42. $g(x)=\frac{x^3}{2a-x},(a,a^2)$

43. Hallar el punto en la parábola $y=3x^2-2x-1$ en el cual la recta tangente es horizontal (paralela al eje X).

44. Hallar la recta tangente horizontal a la curva $y=\frac{e^x}{x}$

45. Hallar la recta tangente horizontal a la curva $y=\frac{e^x}{1+x^2}$

46. Hallar los puntos del gráfico de la función $f(x)=\frac{1}{3}x^3+\frac{1}{2}x^2-6x-\frac{7}{2}$ en los cuales la recta tangente es horizontal (paralela al eje X).

47. Hallar la tangente al gráfico de $f(x)=x^3-3x^2-5$ que es paralela a la recta $3x+y-1=0.$

48. Hallar la tangente al gráfico de $g(x)=\sqrt{x}+2$ que es perpendicular a la recta $2x+y+8=0.$

49. Hallar la parábola $y=ax^2+bx$ que tenga a (2,-12) como punto más bajo.

50. Hallar la parábola $y=ax^2+bx$ que tenga a (4,16) como punto más alto.

51. Hallar la parábola $y=x^2+bx+c$ que es tangente a la recta $2x+y+7=0$ en el punto (-2,-3).

\newpage

# DERIVADAS DE LAS FUNCIONES TRIGONOMETRICAS

En los problemas del 1 al 9 hallar la derivada de la función dada.

1. $f(x)=5senx+2cosx$

2. $g(\theta)=\theta{cot}\theta$

3. $y=tan\alpha sen\alpha$

4. $y=tanx-cotx$

5. $h(t)=\frac{sent}{1+cost}$

6. $f(x)=\frac{tanx}{x}$

7. $g(x)=\frac{1-cosx}{1+cosx}$

8. $y=\frac{sent+cost}{sent-cost}$

9. $y=\frac{tanx-1}{secx}$

10. Si $f(x)=secx-2cosx$, hallar:

a. La recta tangente al gráfico de $f$ en el punto $(\pi3,1).$

b. La recta normal al gráfico de $f$ en el punto $(\pi3,1).$

11. Si la recta tangente al gráfico de función $f(x)=senx$ en el punto $(a, sen a)$ pasa por el origen, probar que se cumple que $tana=a.$

12. Probar que $D_xcosx=-senx$

13. Probar que $D_xcotx=-cosec^2x$

14. Probar que $D_xcosecx=-cosec\quad x\quad cotx.$

\newpage

# DERIVADAS DE LAS FUNCIONES EXPONENCIALES Y LOGARITMICAS

1. $y=\sqrt{x}e^x$

2. $y=\left(\frac{1}{2}\right)^x$

3. $y=x^22^x$

4. $y=x^2e^{-x}$

5. $y=e^x \ln x$

6. $y=2^xlog_2x$

7. $y=\frac{\ln x}{e^x}$

8. $y=\frac{log_2x}{2^x}$

9. $y=\frac{1+\ln x}{1-\ln x}$

10. Hallar la recta tangente horizontal a la curva $y=\frac{e^x}{1+x^2}$

11. Hallar la recta tangente al gráfico de $f(x)=xe^{-x}$ en el punto donde $x=-1.$

12. Hallar la recta tangente al gráfico de $g(x)=\frac{4-x}{\ln x}$ en el punto donde $x=4.$

\newpage

# LA REGLA DE LA CADENA

En los problemas del 1 al 61 derivar la función indicada. Las letras a,b y c denotan constantes.

1. $y=(x^2-3x+5)^3$

2. $f(x)=(15-8x)^4$

3. $g(t)=(2t^3-1)^{-3}$

4. $z=\frac{1}{(5x^5-x^4)^8}$

5. $y=(3x^2-8)^3(-4x^2+1)^4$

6. $f(u)=\frac{2u^3+1}{u^2-1}$

7. $y=\left(\frac{x-1}{x+3}\right)^2$

8. $g(t)=\left(\frac{3t^2+2}{2t^3-1}\right)^2$

9. $y=\sqrt{1-2x}$

10. $u=\sqrt{1+t-2t^2-8t^3}$

11. $h(x)=x^2\sqrt{x^4-1}$

12. $g(x)=\frac{x}{\sqrt{x^2+1}}$

13. $y=\sqrt{3x^2-1}\sqrt[3]{2x+1}$

14. $z=(1-3x^2)^2(\sqrt{x}+1)^-2$

15. $h(t)=\frac{1+t}{\sqrt{1-t}}$

16. $z=\sqrt[3]{\frac{1}{1+t^2}}$

17. $z=\sqrt[3]{b+ax^3}$

18. $f(x)=\frac{x}{b^2\sqrt{b^2+x^2}}$

19. $y=\frac{1-\sqrt{1+x}}{1+\sqrt{1+x}}$

20. $f(x)=\sqrt{(x-a)(x-b)(x-c)}$

21. $y=\sqrt[3]{x+\sqrt{x}}$

22. $y=\sqrt{x+\sqrt{x+\sqrt{x}}}$

23. $y=tan\quad 4x$

24. $y=2cot\frac{x}{2}$

25. $u=cos(x^3)$

26. $v=cos^3x$

27. $y=tan(x^4)+tan^4x$

28. $z=cos\sqrt{x}$

29. $u=\sqrt{cosx}$

30. $y=\sqrt{cos\sqrt{x}}$

31. $y=\sqrt[3]{tan3x}$

32. $y=cot\sqrt[3]{1+x^2}$

33. $y=\frac{4}{\sqrt{secx}}$

34. $y=cosec\frac{1}{x^2}$

35. $y=sen^3\left[\frac{1-\sqrt{x}}{1+\sqrt{x}}\right]$

36. $y=\frac{tanx}{\sqrt{sec^2x+1}}$

37. $y=\sqrt{\frac{1+senx}{1-senx}}$

38. $y=\sqrt{1+cot(x+1/x)}$

39. $y=\frac{cot(x/2)}{\sqrt{1-cot^2(x/2)}}$

40. $y=\sqrt{a\quad sen^2x+\quad bcos^2x}$

41. $y=cos(cos\quad x)$

42. $y=sen(cosx^2)$

43. $y=sen^2(cos\quad 4x)$

44. $y=sen(sen(senx))$

45. $y=cos^2(cos x)+sen^2(senx)$

46. $y=sen(tan\sqrt{senx})$

47. $y=tan(sen^2x)$

48. $y=e^{-3x^2+1}$

49. $y=2^{\sqrt{x}}$

50. $y=x^na^{-x^2}$

51. $y=3^{cot(1/t)}$

52. $y=2^{3^{sen^2x}}$

53. $y=\sqrt{log_5x}$

54. $y=\ln\left(\frac{x}{e^x}\right)$

55. $y=\frac{\ln t}{e^{2t}}$

56. $y=\ln \frac{e^{4x}-1}{e^{4x}+1}$

57. $y=e^{x\ln x}$

58. $y=\ln \left[\frac{x+1}{\sqrt{x-2}}\right]$

59. $y=\ln \left[\frac{x+1}{x-1}\right]^{3/5}$

60. $y=\ln (x^3senx)$

61. $y=\ln cos\frac{x-1}{x}$

62. Si $G(x)=(g(x))^{2/3}\quad g(2)=125\quad y\quad g`(2)=150,\quad hallar\quad G`((2)).$

63. Si $F(t)=[f(sen t)]^2,\quad f(0)=-3\quad y\quad f´(0)=5,\quad hallar F´(0).$

64. Dadas $f(u)=\frac{1}{4}u^3-3u+5\quad y\quad g(x)=\frac{x-1}{x+1}$, hallar la derivada de $f o g$ de dos maneras:

a. Encontrando $(f\quad o\quad g)(x)$ y derivando este resultado.

b. Aplicando la regla de la cadena.

En los ejercicios del 65 al 69, hallar $h´(x)\quad si\quad h(x)=(f\quad o\quad g) (x)=f(g(x)).$

65. $f(u)=u^3-2u^2-5,g(x)=2x-1$

66. $f(v)=\sqrt{v},g(x)=2x^3-4$

67. $f(t)=t^5.g(x)=1-2\sqrt{x}$

68. $f(u)=\frac{b-u}{b+u},g(x)=cx$

69. $f(v)=\frac{1}{v}g(x)=a\sqrt{a^2-x^2}$

En los ejercicios del 70 al 73 hallar $\frac{dy}{dx}$

70. $y=3u^3-4u^4-1,u=x^2-1$

71. $y=v^5,v=3a+2bx$

72. $y=t^4,t=\frac{ax+b}{c}$

73. $y=\frac{1}{\sqrt{v}},v=3x^2-1$

En los ejercicios del 74 al 81, hallar la recta tangente y la recta normal al gráfico de la función dada en el punto ($a,f(a)$), para el valor especificado de $a$.

74. $f(x)=(2x^2-1)^3,a=-1$

75. $f(x)=\frac{3}{(2-x^2)^2},a=0$

76. $f(x)=\frac{x-2}{\sqrt{3x+6}},a=1$

77. $f(x)=\sqrt[3]{x-1},a=-7$

78. $f(x)=\frac{(x-1)^2}{(3x-2)^2},a=\frac{1}{2}$

79. $f(x)=cot^2x,a=\frac{\pi}{4}$

80. $f(x)=|1-x^3|,a=2$

81. $f(x)=|sen5x|,,a=\frac{\pi}{3}$

82. Hallar las rectas tangentes al gráfico de $f(x)=(x-1)(x-2)(x-3)$ en los puntos donde el gráfico corta al eje X.

83. Hallar los puntos en la gráfica de $g(x)=x^2(x-4)^2$ en los cuales la recta tangente es paralela al eje X.

84. Hallar las rectas tangentes al gráfico de $f(x)=\frac{x-4}{x-2}$ en los puntos donde este gráfico corta a los ejes. ¿Qué particularidad tienen estas rectas?

85. Hallar las rectas tangentes al gráfico de $g(x)=\frac{x+4}{x+3}$ que pasan por el origen.

86. Hallar las rectas tangentes al gráfico de $f(x)=3x^2-\ln x$ en el punto (1,3).

87. Hallar las rectas tangentes al gráfico de $y=\ln (1+e^x)$ en el punto $(0, \ln 2).$

88. Sean $f$ y $g$ dos funciones diferenciables tales que $f'(u)=\frac{1}{u}\quad y\quad  f(g(x))=x$.

Probar que $g'(x)=g(x).$

\newpage

# APLICACIONES DE LA DERIVADA

## Valores Máximos y Mínimos

1. Dibuje el gráfico de $f$ a mano y use su boceto para encontrar los valores máximos y mínimos absolutos y locales de $f$.

a. $f(x)=\frac{1}{2}(3x-1),x \le3$

b. $f(x)=2-\frac{1}{3}x,x\ge-2$

c. $f(x)=sinx,0\le x<\pi/2$

d. $f(t)=\text{cos} t,-3\pi/2\le t \le 3\pi/2$

e. $f(x)=\ln x, 0<x\le2$

f. $f(x)=1/x,1<x<3$

g. $f(x)=1-\sqrt{}x$

h. 
$f(x)=\left\{
\begin{matrix}
4-x^2 & si & -2  \le x < 0\\
2x-1 & si & 0  \le x \le 2
\end{matrix}
\right .$

2. Encuentra los números críticos de la función.

a. $f(x)=4+\frac{1}{x}x-\frac{1}{2}x^2$

b. $f(x)=x^3+6x^2-15x$

c. $f(x)=2x^3-3x^2-36x$

d. $g(t)=t^4+t^3+t^2+1$

e. $g(y)=\frac{y-1}{y^2-y+1}$

f. $F(x)=x^{4/5}(x-4)^2$

g. $f(\theta)=2\text{cos}\theta+\text{sin}^2\theta$

h. $f(x)=x^2e^{-3x}$

i. $f(x)=2x^3+x^2+2x$

j. $g(t)=|3t-4|$

k. $g(x)=x^{1/3}-x^{-2/3}$

l. $g(\theta)=4\theta-\text{tan}\theta$

m. $f(x)=x^{-2}\ln x$

n. $h(p)=\frac{p-1}{p2^+4}$

3. Encuentre los valores mínimos absolutos y máximos absolutos de $f$ en el intervalo dado.

a. $f(x)=12+4x-x^2,\quad [0,5]$

b. $f(x)=5+54x-2x^3,\quad [0,4]$

c. $f(x)=2x^3-3x^2-12x+1,\quad [-2,3]$

d. $f(x)=x^3-6x^2+5,\quad [-3,5]$

e. $f(x)=3x^4-4x^3-12x^2+1,\quad [-2,3]$

f. $f(x)=(x^2-1)^3,\quad [-1,2]$

g. $f(t)=t\sqrt{4-t^2},\quad [-1,2]$

h. $f(f)=\frac{x}{x^2-x+1},\quad [0,3]$

i. $f(t)=2\text{cos}t+\text{sin}2t,\quad [0,\pi/2]$

j. $f(t)=t+\text{cot}(\frac{1}{2}t),\quad [\pi/4,7\pi/4]$

k. $f(x)=xe^{-x^2/8}, [-1,4]$

l. $f(x)=x-\ln x,\quad [\frac{1}{2},2]$

m. $f(x)=\ln (x^2+x+1),\quad[-1.1]$

n. $f(x)=x-2\text{tan}^{-1}x,\quad [0,4]$

4. En los siguientes ejercicios: 

a. Use un gráfico para estimar los valores máximos y mínimos absolutos de la función con dos decimales.

b. Use cálculo para encontrar los valores máximos y mínimos exactos.

4.1. $f(x)=x^5-x^3+2,\quad -1\le x\le1$

4.2. $f(x)=e^x+e^{-2x},\quad 0\le x\le1$

4.3. $f(x)=x\sqrt{x-x^2}$

4.4. $f(x)=x-2\text{cos}x,\quad -2\le x\le0$

5. La función proporciona un modelo para el precio promedio de una libra de azúcar blanco de 1993 a 2003.

$$
\begin{matrix}
S(t)=-0.0000327t^5+0.0009037t^4-0.008956t^3\\
+0.03629t^2-0.04458t+0.4074
\end{matrix}
$$

Donde se mide en años desde agosto de 1993. Estime los tiempos en que el azúcar fue más barato y más caro durante el período 1993-2003.

6. En los siguientes ejercicios:

(a) Encuentre los intervalos en los que $f$ aumenta o disminuye.
(b) Encuentre los valores máximos y mínimos locales de $f$.
(c) Encuentre los intervalos de concavidad y los puntos de inflexión.

6.1. $f(x)=2x^3+3x^2-36x$

6.2. $f(x)=4x^3+3x^2-6x+1$

6.3. $f(x)=x^4-2x^2+3$

6.4. $f(x)=\frac{x}{x^2+1}$

6.5. $f(x)=\text{sin}x+\text{cos}x,\quad 0\le x\le2\pi$

6.6. $f(x)=\text{cos}^2x-2\text{sin}x,\quad 0\le x\le 2\pi$

6.7. $f(x)=e^{2x}+e^{-x}$

6.8. $f(x)=x^2\ln x$

6.9. $f(x)=x^2-x-\ln x$

6.10. $f(x)=x^4e^{-x}$

## Derivados y Formas de Gráficos

Dibuje el gráfico de una función que satisfaga todas las condiciones dadas.

1. $f´(x)$ y $f"(x)$ son siempre negativos.

2. Asíntota vertical 

$x=0, f´(x)>0\quad  si\quad  x<-2,$

$f´(x)<0\quad si\quad x>-2 (x\ne0),$

$f"(x)<0\quad si\quad x<0,f"(x)>0\quad si\quad x>0$

3. $f´(0)=f´(2)=f´(4)=0,$

$f´(x)>0\quad si\quad x<0\quad ó\quad 2<x<4,$

$f´(x)<0\quad si\quad x<0\quad ó\quad 2<x>4,$

$f"(x)>0\quad si\quad 1<x<3, f"(x)<0\quad si\quad x<1\quad ó\quad x>3$

4. $f´(1)=f´(-1)=0, f´(x)<0\quad si\quad |x|<1,$

$f´(x)>0\quad si\quad 1<|x|<2,f´(x)=-1\quad si\quad |x|>2,$

$f"(x)<0\quad si\quad -2<x<0,$ punto de inflección $(0,1)$

5. $f´(x)>0\quad si\quad |x|<2, f´(x)<0\quad si\quad |x|>2,$

$f´(-2)=0,\displaystyle\lim_{x\to 2}|f´(x)|=\infty, f"(x)>0\quad si\quad x\ne2$

6. $f´(x)>0\quad si\quad |x|<2, f´(x)<0\quad si\quad |x|>2,$

$f´(2)=0,\displaystyle\lim_{x\to \infty}f(x)=1, f(-x)=-f(x),$

$f"(x)<0\quad si\quad 0<x<3, f"(x)>0\quad si\quad x>3$

7. En los siguientes ejercicios:

a. Encuentre las asíntotas verticales y horizontales.

b. Encuentre los intervalos de aumento o disminución.

c. Encuentre los valores máximos y mínimos locales.

d. Encuentre los intervalos de concavidad y los puntos de inflexión.

e. Use la información de las partes (a) - (d) para esbozar el gráfico de $f$.

7.1 $f(x)=1+\frac{1}{x}-\frac{1}{x^2}$

7.2 $f(x)=\frac{x^2-4}{x^2+4}$

7.3 $f(x)=\sqrt{x^2+1}-x$

7.4 $f(x)=\frac{e^x}{1-e^x}$

7.5 $f(x)=e^{-x^2}$

7.6 $f(x)=x-\frac{1}{6}x^2-\frac{2}{3}\ln x$

7.7 $f(x)=\ln (1-\ln x)$

7.8 $f(x)=e^{\text{arctan} x}$

8. En este ejercicio determine:

a. Si $C(x)$ es el costo de producir unidades de un producto, entonces el costo promedio por unidad es $c(x)=C(x)/x$. Demuestre que si el costo promedio es mínimo, entonces el marginal el costo es igual al costo promedio.

b. Si $C(x)=16,000+200x+4x^{3/2}$, en dólares, encuentre (i) el costo, el costo promedio y el costo marginal a un nivel de producción de 1000 unidades; (ii) el nivel de producción que minimizará el costo promedio; y (iii) el costo promedio mínimo.

9. a) Demuestre que si la ganancia $P(x)$ es un máximo, entonces el ingreso marginal es igual al costo marginal.

b) Si $C(x)=16,000+500x-1.6x^2+0.004x^3$ es la función de costo y $p(x)=1700-7x$ es la función de demanda, encuentre el nivel de producción que maximizará los beneficios.

10. Un equipo de béisbol juega en un estadio que tiene 55,000 espectadores. Con los precios de los boletos en \$10, la asistencia promedio había sido de 27,000. Cuando se redujeron los precios de los boletos a \$8, la asistencia promedio aumentó a 33,000.

a. Encuentre la función de demanda, suponiendo que sea lineal.

b. ¿Cómo deberían establecerse los precios de los boletos para maximizar los ingresos?

11. Durante los meses de verano, Terry fabrica y vende collares en la playa. El verano pasado vendió los collares por \$10 cada uno y sus ventas promediaron 20 por día. Cuando aumentó el precio por \$1, descubrió que el promedio disminuía en dos ventas por día.

a. Encuentre la función de demanda, suponiendo que sea lineal.

b. Si el material de cada collar le cuesta a Terry \$6, ¿cuál debería ser el precio de venta para maximizar su beneficio?

12. Un fabricante ha estado vendiendo 1000 televisores de pantalla plana por semana en \$450 cada uno. Una encuesta de mercado indica que por cada \$10 de descuento ofrecido al comprador, la cantidad de televisores vendidos aumentará en 100 por semana.

a. Encuentre la función de demanda.

b. ¿Qué tan grande es el descuento que la empresa debe ofrecer al comprador para maximizar sus ingresos?

c. Si su función de costo semanal es $C(x)=68,000+150x$, ¿cómo debe el fabricante establecer el tamaño del reembolso para maximizar su beneficio?

13. El gerente de un complejo de apartamentos de 100 unidades sabe por experiencia que todas las unidades estarán ocupadas si el alquiler es \$800 por mes. Una encuesta de mercado sugiere que, en promedio, una unidad adicional permanecerá vacante por cada \$10 de aumento en la renta. ¿Qué renta debería cobrar el gerente para maximizar los ingresos?

\newpage

## Diferenciar la función

1. $f(x)=x^{40}$

2. $f(x)=\pi^2$

3. $f(x)=2-\frac{2}{3}t$

4. $F(x)=\frac{3}{4}x^8$

5. $f(x)=x^3-4x+6$

6. $f(t)=\frac{1}{2}t^6-3t^4+t$

7. $g(x)=x^2(1-2x)$

8. $h(x)=(x-2)(2x+3)$

9. $g(t)=2t^{-3/4}$

10. $B(y)=cy^{-6}$

11. $A(s)=-\frac{12}{s^5}$

12. $y=x^{5/3}-x^{2/3}$

13. $S(p)=\sqrt{p}-p$

14. $y=\sqrt{x}(x-1)$

15. $R(a)=(3a+1)^2$

16. $S(R)=4\pi R^2$

17. $y=\frac{x^2+4x+3}{\sqrt{x}}$

18. $y=\frac{\sqrt{x}+x}{x^2}$

19. $H(x)=(x+x^{-1})^3$

20. $g(u)=\sqrt{2u}+\sqrt{3u}$

21. $u=\sqrt[5]{t}+4\sqrt{t^5}$

22. $v=\left(\sqrt{x}+\frac{1}{\sqrt[3]x}\right)^2$

23. Encuentre la derivada de $f(x)=(1+2x^2)(x-x^2)$ de dos maneras: mediante el uso de la Regla del producto y al realizar la multiplicación primero. ¿Sus respuestas están de acuerdo?

24. Encuentra la derivada de la función

$$F(x)=\frac{x^4-5x^3+\sqrt{x}}{x^2}$$

de dos maneras: usando la Regla del cociente y simplificando primero. Muestra que tus respuestas son equivalentes. ¿Qué método prefieres?

## Diferenciar

25. $V(x)=(2x^3+3)(x^4-2x)$

26. $L(x)=(1+x+x^2)(2-x^4)$

27. $F(y)=\left(\frac{1}{y^2}-\frac{3}{y^4}\right)(y+5y^3)$

28. $J(v)=(v^3-2v)(v^{-4}+v^{-2})$

29. $g(x)=\frac{1+2x}{3-4x}$

30. $f(x)=\frac{x-3}{x+3}$

31. $y=\frac{x^3}{1-x^2}$

32. $y=\frac{x+1}{x^3+x-2}$

33. $y=\frac{v^3-2v\sqrt{v}}{v}$

34. $y=\frac{t}{(t-1)^2}$

35. $y=\frac{t^2+2}{t^4-3t^2+1}$

36. $g(t)=\frac{t-\sqrt{t}}{t^{1/3}}$

37. $y=ax^2+bx+c$

38. $y=A+\frac{B}{x}+\frac{C}{x^2}$

39. $f(t)=\frac{2t}{2+\sqrt{t}}$

40. $y=\frac{cx}{1+cx}$

41. $y=\sqrt[3]{t}(t^2+t+t^-1)$

42. $y=\frac{u^6-2u^3+5}{u^2}$

43. $f(x)=\frac{x}{x+\frac{c}{x}}$

44. $f(x)=\frac{ax+b}{cx+d}$

45. El polinomio general de grado tiene la forma

$$P(x)=a_nx^n+a_{n-1}x^{n-1}+...+a_2x^2+a_1x+a_0$$

46. Encuentre ecuaciones de la línea tangente y línea normal a la curva en el punto dado.

46.1. $y=x+\sqrt{x},(1,2)$

46.2. $y=(1+2x)^2, (1,9)$

46.3. $y=\frac{3x+1}{x^2+1},(1,2)$

46.4. $y=\frac{\sqrt{x}}{x+1},(4,0.4)$

47. Encuentra la primera y segunda derivada de la función.

47.1. $f(x)=x^4-3x^3+16x$

47.2. $G(r)=\sqrt{r}+\sqrt[3]{r}$

47.3. $f(x)=\frac{x^2}{1+2x}$

47.4. $f(x)=\frac{1}{3-x}$

## Diferenciar

1. $f(x)=3x^2-2\text{cos}x$y

2. $f(x)=\sqrt{x}\text{sin}x$

3. $f(x)=\text{sin}x+\frac{1}{2}\text{cot}x$

4. $y=2\text{sec}x-\text{csc}x$

5. $y=\text{sec}\theta\text{tan}\theta$

6. $g(t)=4\text{sec}t+\text{tan}t$

7. $y=c\text{cos}t+t^2\text{sin}t$

8. $y=u(a\text{cos}u+b\text{cot}u)$

9. $y=\frac{x}{2-\text{tan}x}$

10. $y=\text{sin}\theta\text{cos}\theta$

11. $f(\theta)=\frac{\text{sec}\theta}{1+\text{sec}\theta}$

12. $y=\frac{\text{cos}x}{1-\text{sin}x}$

13. $y=\frac{t\text{sin}t}{1+t}$

14. $y=\frac{1-\text{sec}x}{\text{tan}x}$

15. $h(\theta)=\theta\text{csc}\theta-\text{cot}\theta$

16. $y=x^2\text{sin}x\text{tan}x$

17. Probar que $\frac{d}{dx}(\text{csc}x)=-\text{csc}x\text{cot}x$

18. Probar que $\frac{d}{dx}(\text{sec}x)=\text{sec}x\text{tan}x$

19. Probar que $\frac{d}{dx}(\text{cot}x)=-\text{csc}^2x$.

20. Demuestre, usando la definición de derivada, que si $f(x)=\text{x}=\text{cos}x$, entonces $f´(x)=-\text{sin}x$

En los ejercicios 21 al 24 Encuentra una ecuación de la recta tangente a la curva en el punto dado.

21. $y=\text{sec}x,\quad (\pi/3,2)$

22. $y=(1+x)\text{cos}x,\quad (0,1)$

23. $y=\text{cos}x-\text{sin}x,\quad (\pi,-1)$

24. $y=x+\text{tan}x,\quad (\pi,\pi)$

\newpage

En los ejercicios 1 al 6, Escriba la función compuesta en la forma $f(g(x))$. [Identifique la función interna $u=g(x)$ y la función externa $y=f(u)$.] Luego encuentre la derivada $dy/dx$.

1. $y=\sqrt[3]{1+4x}$

2. $y=(2x^3+5)^4$

3. $y=\text{tan}\pi x$

4. $y=\text{sin}(\text{cot}x)$

5. $y=\sqrt{\text{sin}x}$

6. $y=\text{sin}\sqrt{x}$

En los ejercicios 7 al 46, Encuentra la derivada de la función.

7. $F(x)=(x^4+3x^2-2)^5$

8. $F(x)=(4x-x^2)^{100}$

9. $F(x)=\sqrt{1-2x}$

10. $f(x)=\frac{1}{(1+\text{sec}x)^2}$

11. $f(z)=\frac{1}{z^2+1}$

12. $f(t)=\sqrt[3]{1+\text{tan}t}$

13. $y=\text{cos}(a^3+x^3)$

14. $y=a^3+\text{cos}^3x$

15. $y=x\text{sec}kx$

16. $y=3\text{cot}n\theta$

17. $f(x)=(2x-3)^4(x^2+x+1)^5$

18. $g(h)=(x^2+1)^3(x^2+2)^6$

19. $h(t)=(t+1)^{2/3}(2t^2-1)^3$

20. $F(t)=(3t-1)^4(2t+1)^{-3}$

21. $y=\left(\frac{x^2+1}{x^2-1}\right)^3$

22. $f(s)=\sqrt{\frac{s^2+1}{s^2+4}}$

23. $y=\text{sin}(x\text{cos}x)$

24. $f(x)=\frac{x}{\sqrt{7-3x}}$

25. $F(z)=\sqrt{\frac{z-1}{z+1}}$

26. $G(y)=\frac{(y-1)^4}{(y^2+2y)^5}$

27. $y=\frac{r}{\sqrt{r^2+1}}$

28. $y=\frac{\text{cos}\pi x}{\text{sin}\pi x+\text{cos}\pi x}$

29. $y=\text{sin}\sqrt{1+x2}$

30. $F(v)=\left(\frac{v}{v^3+1}\right)^6$

31. $y=\text{sin}(\text{tan}2x)$

32. $y=\text{sec}^2(m\theta)$

33. $y=\text{sec}^2x+\text{tan}^2x$

34. $y=x\text{sin}\frac{1}{x}$

35. $y=\left(\frac{1-\text{cos}2x}{1+\text{cos}2x}\right)^4$

36.$f(t)=\sqrt{\frac{t}{t^2+4}}$

37. $y=\text{cot}^2(\text{sin}\theta)$

38. $y=(ax+\sqrt{x^2+b^2})^{-2}$

39. $y=[x^2+(1-3x)^5]^3$

40. $y=\text{sin}(\text{sin(sin x)})$

41. $y=\sqrt{x+\sqrt{x}}$

42. $y=\sqrt{x+\sqrt{x+\sqrt{x}}}$

43. $g(x)=(2r\text{sin}rx+n)^p$

44. $y=\text{cos}^4(\text{sin}^3x)$
 
45. $y=\text{cos}\sqrt{\text{sin}(tan \pi x)}$

46. $y=[x+(x+\text{sin}^2x^3)]^4$

En los ejercicios 47 al 50, Encuentra la primera y segunda derivada de la función.

47. $y=\text{cos}(x^2)$

48. $y=cos^2x$

49. $H(t)=\text{tan}3t$

50. $y=\frac{4x}{\sqrt{x+1}}$

\newpage

En los siguientes ejercicios calcula $y'$

1. $y=(x^2+x^3)^4$

2. $y=\frac{1}{\sqrt{x}}-\frac{1}{\sqrt[5]{x^3}}$

3. $y=\frac{x^2-x+2}{\sqrt{x}}$

4. $y=\frac{\text{tan}x}{1+\text{cos}x}$

5. $y=x^2\text{sin}\pi x$

6. $y=\left(x+\frac{1}{x^2}\right)^{\sqrt{^7}}$

En los siguientes ejercicios, Dibuje el gráfico de $f$ a mano y use su boceto para encontrar los valores máximos y mínimos absolutos y locales de $f$.

1. $f(x)=\frac{1}{2}(3x-1),\quad x\le3$

2. $f(x)=2-\frac{1}{3}x,\quad x\ge-2$

3. $f(x)=1/x,\quad x\ge1$

4. $f(x)=1/x,\quad 1<x<3$

5. $f(x)=\text{sin}x,\quad 0\le x<\pi/2$

6. $f(x)=\text{sin}x,\quad 0<x\le\pi/2$

7. $f(x)=\text{sin}x,\quad -\pi/2\le x\le\pi/2$

8. $f(t)=\text{cos},t\quad -3\pi/2\le t\le 3\pi/2$

9. $f(x)=1+(x+1)^2,\quad -2\le x <5$

10. $f(x)=|x|$

11. $f(X)=1-\sqrt{x}$

12. $f(x)=1-x^3$

13. $f(x)=\left\{
\begin{matrix}
1-x & si & 0\le x < 2\\
2x-4 & si & 2\le x \le 3
\end{matrix}
\right .$

14. $f(x)=\left\{
\begin{matrix}
4-x^2 & si & -2\le x < 0\\
2x-1 & si & 0\le x \le 2
\end{matrix}
\right .$

En los siguientes ejercicios, Encuentra los números críticos de la función.

1. $f(x)=4+\frac{1}{3}x-\frac{1}{2}x^2$

2. $f(x)=x^3+6x^2-15x$

3. $f(x)=2x^3-3x^2-36x$

4. $f(x)=2x^3+x^2+2x$

5. $g(t)=t^4+t^3+t^2+1$

6. $g(t)=|3t-4|$

7. $g(y)=\frac{y-1}{y^2-y+1}$

8. $h(p)=\frac{p-1}{p^2+4}$

9. $h(t)=t^{3/4}-2t^{1/4}$

10. $g(x)=x^{1/3}-x^{-2/3}$

11. $F(x)=x^{4/5}(x-4)^2$

12. $g(\theta)=4\theta-\text{tan}\theta$

13. $f(\theta)=2\text{cos}\theta+\text{sin}^2\theta$

14. $g(x)=\sqrt{1-x^2}$

En los siguientes ejercicios. Encuentre los valores absolutos mínimos y absolutos máximos en el intervalo dado.

1. $f(x)=12+4x-x^2,\quad [0,5]$

2. $f(x)=5+54x-2x^3,\quad [0,4]$

3. $f(x)=2x^3-3x^2-12x+1,\quad [-2,3]$

4. $f(x)=x^3-6x^2+5,\quad [-3,5]$

5. $f(x)=3x^4-4x^3-12x^2+1,\quad [-2,3]$

6. $f(x)=(x^2-1)^3,\quad [-1,2]$

7. $f(x)=x+\frac{1}{x},\quad [0.2,4]$

8. $f(x)=\frac{x}{x^2-x+1},\quad [0,3]$

9. $f(t)=t\sqrt{4-t^2},\quad [-1,2]$

10. $f(t)=\sqrt[3]{t}(8-t),\quad [0,8]$

11. $f(t)=2\text{cos}t+\text{sin}2t,\quad [0,\pi/2]$

12. $f(t)=t+\text{cot}(t/2),\quad [\pi/4,7\pi/4]$

En los siguientes ejercicios, 

a) Use un gráfico para estimar los valores máximos y mínimos absolutos de la función con dos decimales.

b) Use cálculo para encontrar los valores máximos y mínimos exactos

1. $f(x)=x^5-x^3+2,\quad -1\le x\le 1$

2. $f(x)=x^4-3x^3+3x^2-x,\quad 0\le x \le 2$

3. $f(x)=x\sqrt{x-x^2}$

4. $f(x)=x-2\text{cos}x,\quad -2\le x \le 0$
