---
title: "Ejercicios de Integrales"
subtitle: "Cálculo"
author: "http://synergy.vision/"
output:
  pdf_document:
      toc: yes
      toc_depth: 4
      keep_tex: yes
      includes:
        in_header: ./preambulo.tex
  html_document: default
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newpage

Use la Parte 1 del Teorema Fundamental del Cálculo para encontrar la derivada de la función.

1. $g(x)=\displaystyle\int_{1}^{x}\frac{1}{t^3+1}dt$

2. $g(x)=\displaystyle\int_{1}^{x}(2+t^4)^5dt$

3. $g(s)=\displaystyle\int_{5}^{s}(t-t^2)^8dt$

4. $g(r)=\displaystyle\int_{0}^{r}\sqrt{x^2+4}dx$

5. $F(x)=\displaystyle\int_{x}^{\pi}\sqrt{1+\text{sec}t}dt$

$$\left[\displaystyle\int_{x}^{\pi}\sqrt{1+\text{sec}t}dt=-\displaystyle\int_{\pi}^{x} \sqrt{1+\text{sec}}tdt\right]$$
6. $G(x)=\displaystyle\int_{1}^{x}\text{cos}\sqrt{t}dt$

7. $h(x)=\displaystyle\int_{2}^{1/x}\text{sin}^4tdt$

8. $h(x)=\displaystyle\int_{1}^{\sqrt{x}}\frac{z^2}{z^4+1}dz$

9. $y=\displaystyle\int_{0}^{tanx}\sqrt{t+\sqrt{t}}dt$

10. $y=\displaystyle\int_{0}^{x^4}\text{cos}^2\theta d\theta$

11. $y=\displaystyle\int_{1-3x}^{1}\frac{u^3}{1+u^2}du$

12. $y=\displaystyle\int_{sinx}^{1}\sqrt{1+t^2}dt$

Evaluar la integral.

13. $\displaystyle\int_{-1}^{2}(x^3-2x)dx$

14. $\displaystyle\int_{-1}^{1}x^{100}dx$

15. $\displaystyle\int_{1}^{4}(5-2t+3t^2)dt$

16. $\displaystyle\int_{0}^{1}(1+\frac{1}{2}u^4-\frac{2}{5}u^9)$

17. $\displaystyle\int_{1}^{9}\sqrt{x}dx$

18. $\displaystyle\int_{1}^{8}x^{-2/3}dx$

19. $\displaystyle\int_{\pi/6}^{\pi}\text{sin}\theta d \theta$

20. $\displaystyle\int_{-5}^{5}\pi dx$

21. $\displaystyle\int_{0}^{1}(u+2)(u-3)du$

22. $\displaystyle\int_{0}^{4}(4-t)\sqrt{t}dt$

23. $\displaystyle\int_{1}^{9}\frac{x-1}{\sqrt{x}}dx$

24. $\displaystyle\int_{0}^{2}(y-1)(2y+1)$

25. $\displaystyle\int_{0}^{\pi/4}\text{sec}^2tdt$

26. $\displaystyle\int_{0}^{\pi/4}\text{sec}\theta\quad \text{tan}\theta\quad d\theta$

27. $\displaystyle\int_{1}^{2}(1+2y)^2dy$

28. $\displaystyle\int_{1}^{2}\frac{s^4+1}{s^2}ds$

29. $\displaystyle\int_{1}^{2}\frac{v^5+3v^6}{v^4}dv$

30. $\displaystyle\int_{1}^{18}\sqrt{\frac{3}{z}}dz$

31. $\displaystyle\int_{0}^{\pi}f(x)dx\quad \text{donde}\quad 
f(x)=\left\{
\begin{matrix}
\text{sin} x & \text{si} & 0\le & x<\pi/2\\
\text{cos} x & \text{si} & \pi/2\le & x\le\pi
\end{matrix}
\right .$

32. $\displaystyle\int_{-2}^{2}f(x)dx\quad \text{donde}\quad 
f(x)=\left\{
\begin{matrix}
2 & \text{si} & -2\le & x \le 0\\
4 - x^2 & \text{si} & 0 < & x\le 2
\end{matrix}
\right .$


¿Qué está mal con la ecuación?

33. $\displaystyle\int_{-2}^{1}x^{-4}dx=\frac{x^{-3}}{-3}\big|_{-2}^{1}=-\frac{3}{8}$

34. $\displaystyle\int_{-1}^{2}\frac{4}{x^3}dx=-\frac{2}{x^2}\big|_{-1}^{2}=\frac{3}{2}$

35. $\displaystyle\int_{\pi/3}^{\pi}\sec\theta\tan\theta d\theta=\sec\theta\big|_{\pi/3}^{\pi}=-3$

36. $\displaystyle\int_{0}^{\pi}\sec^2 x dx=\tan x\big|_{0}^{\pi}=0$

Use un gráfico para dar una estimación aproximada del área de la región que se encuentra debajo de la curva dada. Luego encuentra el área exacta.

37. $y=\sqrt[3]{x},\quad 0\le x \le 27$

38. $y=x^{-4},\quad 1\le x \le 6$

39. $y=\sin x,\quad 0\le x \le \pi$

40. $y=\sec^2x,\quad 0\le x \le\pi/3$

Evaluar la integral.

41. $\displaystyle\int_{1}^{9}\frac{1}{2x}dx$

42. $\displaystyle\int_{0}^{1}10^xdx$

43. $\displaystyle\int_{1/2}^{\sqrt{3/2}}\frac{6}{\sqrt{1-t^2}}dt$

44. $\displaystyle\int_{0}^{1}\frac{4}{t^2+1}dt$

45. $\displaystyle\int_{-1}^{1}e^{u+1}du$

46. $\displaystyle\int_{1}^{2}\frac{4+u^2}{u^3}du$

\newpage

Verificar por diferenciación que la fórmula es correcta.

1. $\displaystyle\int\frac{1}{x^2\sqrt{1+x^2}}dx=-\frac{\sqrt{1+x^2}}{x}+C$

2. $\displaystyle\int\cos^2xdx=\frac{1}{2}x+\frac{1}{4}\sin 2x+C$

3. $\displaystyle\int\cos^3xdx= \sin x-\frac{1}{3}\sin^3x+C$

4. $\displaystyle\int\frac{x}{\sqrt{a+bx}}dx=\frac{2}{3b^2}(bx-2a)\sqrt{a+bx}+C$

Encuentra la integral general indefinida.

5. $\displaystyle\int(x^2+x^{-2})dx$

6. $\displaystyle\int(\sqrt{x^3}+\sqrt[3]{x^2})dx$

7. $\displaystyle\int(x^4-\frac{1}{2}x^3+\frac{1}{4}x-2)dx$

8. $\displaystyle\int(y^3+1.8y^2-2.4y)dy$

9. $\displaystyle\int(u+4)(2u+1)du$

10. $\displaystyle\int v(v^2+2)^2dv$

11. $\displaystyle\int\frac{x^3-2\sqrt{x}}{x}dx$

12. $\displaystyle\int\left(u^2+1+\frac{1}{u^2}\right)du$

13. $\displaystyle\int(\theta-\csc\theta\cot\theta)d\theta$

14. $\displaystyle\int\sec t(\sec t+\tan t)dt$

15. $\displaystyle\int(1+\tan^2\alpha)d\alpha$

16. $\displaystyle\int\frac{\sin2x}{\sin x}dx$

Evaluar la integral.

17. $\displaystyle\int_{-2}^{3}(x^2-3)dx$

18. $\displaystyle\int_{1}^{2}(4x^3-3x^2+2x)dx$

19. $\displaystyle\int_{-2}^{0}(\frac{1}{2}t^4+\frac{1}{4}t^3-t)dt$

20. $\displaystyle\int_{0}^{3}(1+6w^2-10w^4)dw$

21. $\displaystyle\int_{0}^{2}(2x-3)(4x^2+1)dx$

22. $\displaystyle\int_{-1}^{1}t(1-t)^2dt$

23. $\displaystyle\int_{0}^{\pi}(4\sin\theta-3\cos\theta)d\theta$

24. $\displaystyle\int_{1}^{2}\left(\frac{1}{x^2}-\frac{4}{x^3}\right)dx$

25. $\displaystyle\int_{1}^{4}\left(\frac{4+6u}{\sqrt{u}}\right)du$

26. $\displaystyle\int_{1}^{2}\left(x+\frac{1}{x}\right)^2dx$

27. $\displaystyle\int_{1}^{2}\sqrt{\frac{5}{x}}dx$

28. $\displaystyle\int_{1}^{9}\frac{3x-2}{\sqrt{x}}dx$

29. $\displaystyle\int_{1}^{4}\sqrt{t}(1+t)dt$

30. $\displaystyle\int_{\pi/4}^{\pi/3}\csc^2\theta d\theta$

31. $\displaystyle\int_{0}^{\pi/4}\frac{1+\cos^2\theta}{\cos^2\theta}d\theta$

32. $\displaystyle\int_{0}^{\pi/3}\frac{\sin\theta+\sin\theta\tan^2\theta}{\sec^2\theta}d\theta$

33. $\displaystyle\int_{1}^{64}\frac{1+\sqrt[3]{x}}{\sqrt{x}}dx$

34. $\displaystyle\int_{1}^{8}\frac{x-1}{\sqrt[3]{x^2}}dx$

35. $\displaystyle\int_{0}^{1}(\sqrt[4]{x^5}+\sqrt[5]{x^4})dx$

36. $\displaystyle\int_{0}^{1}(1+x^2)^3dx$

37. $\displaystyle\int_{2}^{5}|x-3|dx$

38. $\displaystyle\int_{0}^{2}|2x-1|dx$

39. $\displaystyle\int_{-1}^{2}(x-2|x|)dx$

40. $\displaystyle\int_{0}^{3\pi/2}|\sin x|dx$

41. $\displaystyle\int(\sin x + \sin h x )dx$

42. $\displaystyle\int_{-10}^{10}\frac{2e^{x}}{\sinh x + \cosh x}dx$

43. $\displaystyle\int\left(x^2+1+\frac{1}{x^2+1}\right)dx$

44. $\displaystyle\int_{1}^{2}\frac{(x-1)^3}{x^2}dx$

45. $\displaystyle\int_{0}^{1/\sqrt{3}}\frac{t^2-1}{t^4-1}dt$

Evalúa la integral haciendo la sustitución dada.

1. $\displaystyle\int\sin\pi x dx,\quad u=\pi x$

2. $\displaystyle\int x^3(2+x^4)^5dx,\quad u=2+x^4$

3. $\displaystyle\int x^2\sqrt{x^3+1}dx,\quad u=x^3+1$

4. $\displaystyle\int\frac{dt}{(1-6t)^4},\quad u=1-6t$

5. $\displaystyle\int\cos^3\theta\sin\theta d\theta,\quad u=\cos\theta$

6. $\displaystyle\int\frac{\sec^2(1/x)}{x^2}dx,\quad u=1/x$

Evaluar la integral indefinida.

7. $\displaystyle\int x\sin(x^2)dx$

8. $\displaystyle\int x^2\cos(x^3)dx$

9. $\displaystyle\int(1-2x)^9dx$

10. $\displaystyle\int(3t+2)^{2.4}dt$

11. $\displaystyle\int(x+1)\sqrt{2x+x^2}dx$

12. $\displaystyle\int\sec^22\theta d\theta$

13. $\displaystyle\int\sec3t\tan3t dt$

14. $\displaystyle\int u\sqrt{1-u^2}du$

15. $\displaystyle\int\frac{a+bx^2}{\sqrt{3ax+bx^3}}dx$

16. $\displaystyle\int\frac{\sin\sqrt{x}}{\sqrt{x}}dx$

17. $\displaystyle\int\sec^2\theta\tan^3\theta d\theta$

18. $\displaystyle\int\cos^4\theta\sin\theta d\theta$

19. $\displaystyle\int(x^2+1)(x^3+3x)^4dx$

20. $\displaystyle\int\sqrt{x}\sin(1+x^{3/2})dx$

21. $\displaystyle\int\frac{\cos x}{\sin^2 x}dx$

22. $\displaystyle\int\frac{\cos(\pi/x)}{x^2}dx$

23. $\displaystyle\int\frac{z^2}{\sqrt[3]{1+z^3}}dz$

24. $\displaystyle\int\frac{dt}{\cos^2t\sqrt{1+\tan t}}$

25. $\displaystyle\int\sqrt{\cot x}\csc^2 xdx$

26. $\displaystyle\int\sin t \sec^2(\cos t)dt$

27. $\displaystyle\int\sec^3 x \tan x dx$

28. $\displaystyle\int x^2\sqrt{2+x}dx$

29. $\displaystyle\int x(2x+5)^8dx$

30. $\displaystyle\int x^3\sqrt{x^2+1}dx$

Evalúa la integral indefinida. Ilustre y compruebe que su respuesta es razonable graficando tanto la función como su antiderivada (tomar $C=0$).

31. $\displaystyle\int x (x^2-1)^3dx$

32. $\displaystyle\int\tan^2 \theta \sec^2 \theta d\theta$

33. $\displaystyle\int\sin^3 x \cos x dx$

34. $\displaystyle\int\sin x \cos^4 x dx$

Evaluar la integral definida.

35. $\displaystyle\int_{0}^{1}\cos(\pi t/2)dt$

36. $\displaystyle\int_{0}^{1}(3t-1)^{50}dt$

37. $\displaystyle\int_{0}^{1}\sqrt[3]{1+7x}dx$

38. $\displaystyle\int_{0}^{\sqrt{\pi}}x \cos(x^2)dx$

39. $\displaystyle\int_{0}^{\pi}\sec^2(t/4)dt$

40. $\displaystyle\int_{1/6}^{1/2}\csc\pi t\cot \pi t dt$

41. $\displaystyle\int_{-\pi/4}^{\pi/4}(x^3+x^4\tan x)dx$

42. $\displaystyle\int_{0}^{\pi/2}\cos x \sin(\sin x)dx$

43. $\displaystyle\int_{0}^{13}\frac{dx}{\sqrt[3](1+2x)^2}$

44. $\displaystyle\int_{0}^{a}x\sqrt{a^2-x^2}dx$

45. $\displaystyle\int_{0}^{a}x\sqrt{x^2+a^2}dx\quad (a>0)$

46. $\displaystyle\int_{-\pi/3}^{\pi/3}x^4\sin x dx$

47. $\displaystyle\int_{1}^{2}x\sqrt{x-1}dx$

48. $\displaystyle\int_{0}^{4}\frac{x}{\sqrt{1+2x}}dx$

49. $\displaystyle\int_{1/2}^{1}\frac{\cos(x^{-2})}{x^3}dx$

50. $\displaystyle\int_{0}^{T/2}\sin(2\pi t/T-\alpha)dt$

51. $\displaystyle\int_{0}^{1}\frac{dx}{(1+\sqrt{x})^4}$

Evaluar la integral.

52. $\displaystyle\int\frac{dx}{5-3x}$

53. $\displaystyle\int e^x\sin(e^x)dx$

54. $\displaystyle\int\frac{(\ln x)^2}{x}dx$

55. $\displaystyle\int\frac{dx}{ax+b}(a\ne0)$

56. $\displaystyle\int e^{\tan x}\sec^2xdx$

57. $\displaystyle\int e ^{\cos t}\sin t dt$

58. $\displaystyle\int e^{\tan x}\sec^2x dx$

59. $\displaystyle\int\frac{\tan^{-1}x}{1+x^2}dx$

60. $\displaystyle\int\frac{1+x}{1+x^2}dx$

61. $\displaystyle\int\frac{\sin(\ln x)}{x}dx$

62. $\displaystyle\int\frac{\sin 2x}{1+\cos^2x}dx$

63. $\displaystyle\int\frac{\sin 2x}{1+cos2x}dx$

64. $\displaystyle\int\frac{\sin x}{1+\cos^2x}dx$

65. $\displaystyle\int\cot x dx$

66. $\displaystyle\int\frac{\sin x}{1+\cos^2x}dx$

67. $\displaystyle\int_{e}^{e4}\frac{dx}{x\sqrt{\ln x}}$

68. $\displaystyle\int_{0}^{1}xe^{-x2}dx$

69. $\displaystyle\int_{0}^{1}\frac{e^z+1}{e^z+z}dz$

70. $\displaystyle\int_{0}^{1/2}\frac{\sin^{-1}}{\sqrt{1-x^2}}dx$

71. $\displaystyle\int_{1}^{2}(8x^3+3x^2)dx$

72. $\displaystyle\int_{0}^{T}(x^4-8x+7)dx$

73. $\displaystyle\int_{0}^{1}(1-x^9)dx$

74. $\displaystyle\int_{0}^{1}(\sqrt[4]{u}+1)^2du$

75. $\displaystyle\int_{0}^{1}y(y^2+1)^5dy$

76. $\displaystyle\int_{0}^{2}y^2\sqrt{1+y^3}dy$

77. $\displaystyle\int_{1}^{5}\frac{dt}{(t-4)^2}$

78. $\displaystyle\int_{0}^{1}\sin(3\pi t)dt$

79. $\displaystyle\int_{0}^{1}v^2\cos(v^3)dv$

80. $\displaystyle\int_{-1}^{1}\frac{\sin x }{1+x^2}dx$

81. $\displaystyle\int_{-\pi/4}^{\pi/4}\frac{t^4\tan t}{2+\cos t}dt$

82. $\displaystyle\int\frac{x+2}{\sqrt{x^2+4x}}dx$

83. $\displaystyle\int\sin \pi t \cos \pi t dt$

84. $\displaystyle\int\sin x \cos(\cos x)dx$

85. $\displaystyle\int_{0}^{\pi/8}\sec2\theta \tan 2\theta d\theta$

86. $\displaystyle\int_{0}^{\pi/4}(1+\tan t)^3\sec^2t dt$

87. $\displaystyle\int_{0}^{3}|x^2-4|dx$

88. $\displaystyle\int_{0}^{4}|\sqrt{x}-1|dx$

Encuentra la derivada de la función.

89. $F(x)=\displaystyle\int_{0}^{x}\frac{t^2}{1+t^3}dt$

90. $F(x)=\displaystyle\int_{x}^{1}\sqrt{t+\sin t}dt$

91. $g(x)=\displaystyle\int_{0}^{x^4}\cos(t^2)dt$

92. $g(x)=\displaystyle\int_{1}^{\sin x}\frac{1-t^2}{1+t^4}dt$

93. $y=\displaystyle\int_{\sqrt{x}}^{x}\frac{\cos\theta}{\theta}d\theta$

94. $y=\displaystyle\int_{2x}^{3x+1}\sin(t^4)dt$


\newpage

1. $\displaystyle\int\frac{\sqrt[5]{x^3}+\sqrt[6]{x}}{\sqrt{x}}dx.$

2. $\displaystyle\int\frac{dx}{\sqrt{x-1}+\sqrt{x+1}}.$

3. $\displaystyle\int\frac{e^x+e^{2x}+e^{3x}}{e^{4x}}dx.$

4. $\displaystyle\int\frac{a^x}{b^x}dx.$

5. $\displaystyle\int tg^2 x dx.$

6. $\displaystyle\int\frac{dx}{a^2+x^2}.$

7. $\displaystyle\int\frac{dx}{\sqrt{a^2-x^2}}.$

8. $\displaystyle\int\frac{dx}{1+senx}.$

9. $\displaystyle\int\frac{8x^2+6x+4}{x+1}dx.$

10. $\displaystyle\int\frac{1}{\sqrt{2x-x^2}}dx.$

11. $\displaystyle\int e^x\text{sen}e^xdx.$

12. $\displaystyle\int xe^{-x^2}dx.$

13. $\displaystyle\int\frac{logx}{x}dx.$

14. $\displaystyle\int\frac{e^x dx}{e^{2x}+2e^x+1}.$

15. $\displaystyle\int e^{x^2}e^x dx.$

16. $\displaystyle\int\frac{x dx}{\sqrt{1-x^4}}.$

17. $\displaystyle\int\frac{e\sqrt{x}}{\sqrt{x}}dx.$

18. $\displaystyle\int x\sqrt{1-x^2}dx.$

19. $\displaystyle\int log(\cos x) tg x dx.$

20. $\displaystyle\int\frac{log(log x)}{x log x}dx.$

21. $\displaystyle\int x^2e^xdx.$

22. $\displaystyle\int x^3e^{x^2}dx.$

23. $\displaystyle\int e^{ax}\ sen bx dx.$

24. $\displaystyle\int x^2\ senx dx.$

25. $\displaystyle\int (log x)^3dx.$

26. $\displaystyle\int\frac{log(log x)}{x}dx.$

27. $\displaystyle\int \ sec^3 x dx.$

28. $\displaystyle\int\cos(log x)dx.$

29. $\displaystyle\int \sqrt{x}log x dx.$

30. $\displaystyle\int x(log x)^2dx.$

31. $\displaystyle\int\frac{dx}{\sqrt{1-x^2}}.$

32. $\displaystyle\int\frac{dx}{\sqrt{1+x^2}}.$

33. $\displaystyle\int\frac{dx}{\sqrt{x^2-1}}.$

34. $\displaystyle\int\frac{dx}{x\sqrt{x^2-1}}.$

35. $\displaystyle\int\frac{dx}{x\sqrt{1-x^2}}.$

36. $\displaystyle\int\frac{dx}{x\sqrt{1+x^2}}.$

37. $\displaystyle\int x^2\sqrt{1-x^2}dx.$

38. $\displaystyle\int\sqrt{1-x^2}dx.$

39. $\displaystyle\int\sqrt{1+x^2}dx.$

40. $\displaystyle\int\sqrt{x^2-1}dx.$

41. $\displaystyle\int\frac{dx}{1+\sqrt{x+1}}.$

42. $\displaystyle\int\frac{dx}{1+e^x}.$

43. $\displaystyle\int\frac{dx}{\sqrt{x}+\sqrt[3]x}.$

44. $\displaystyle\int\frac{dx}{\sqrt{1+e^x}}.$

45. $\displaystyle\int\frac{dx}{2+tgx}.$

46. $\displaystyle\int\frac{dx}{\sqrt{\sqrt{x+1}}}.$

47. $\displaystyle\int\frac{4^x+1}{2^x+1}dx.$

48. $\displaystyle\int\ e\sqrt{x}dx.$

49. $\displaystyle\int\frac{\sqrt{1-x}}{1-\sqrt{x}}dx.$

50. $\displaystyle\int\sqrt{\frac{x-1}{x+1}}.\frac{1}{x^2}dx.$

51. $\displaystyle\int\frac{2x^2+7x-1}{x^3+x^2-x-1}dx.$

52. $\displaystyle\int\frac{2x+1}{x^3-3x^2+3x-1}dx.$

53. $\displaystyle\int\frac{x^3+7x^2-5x+5}{(x-1)^2(x+1)^3}dx.$

54. $\displaystyle\int\frac{2x^2+x+1}{(x+3)(x-1)^2}dx.$

55. $\displaystyle\int\frac{x+4}{x^2+1}dx.$

56. $\displaystyle\int\frac{x^3+x+2}{x^4+2x^2+1}dx.$

57. $\displaystyle\int\frac{3x^2+3x+1}{x^3+2x^2+2x+1}dx.$

58. $\displaystyle\int\frac{dx}{x^4+1}.$

59. $\displaystyle\int\frac{2x}{(x^2+x+1)^3}dx.$

60. $\displaystyle\int\frac{3x}{(x2+x+1)^3}dx.$

61. $\displaystyle\int\frac{\text{arctg x}}{1+x^2}dx.$

62. $\displaystyle\int\frac{x\text{arctg x}}{(1+x^2)^3}.$

63. $\displaystyle\int\log \sqrt{1+x^2}dx.$

64. $\displaystyle\int\ x log\sqrt{1+x^2}dx.$

65. $\displaystyle\int\frac{x^2-1}{x^2+1}.\frac{1}{\sqrt{1+x^4}}dx.$

66. $\displaystyle\int\text{arcsen}\sqrt{x}dx.$

67. $\displaystyle\int\frac{x}{1+senx}dx.$

68. $\displaystyle\int e^{senx}.\frac{xcos^3x-senx}{cos^2x}dx.$

69. $\displaystyle\int\sqrt{tgx}dx.$

70. $\displaystyle\int\frac{dx}{x^6+1}.$

71. $\displaystyle\int\log(a^2+x^2)dx.$

72. $\displaystyle\int\frac{1+cosx}{sen^2x}dx.$

73. $\displaystyle\int\frac{x+1}{\sqrt{4-x^2}}dx.$

74. $\displaystyle\int\ x\text{arctg x}dx.$

75. $\displaystyle\int sen^3 x dx.$

76. $\displaystyle\int\frac{sen^3 x}{cos^2 x}dx.$

77. $\displaystyle\int x^2\text{arctg x}dx.$

78. $\displaystyle\int\frac{x dx}{\sqrt{x^2-2x+2}}.$

79. $\displaystyle\int sec^3x\quad tg\quad x\quad dx.$

80. $\displaystyle\int x\quad tg^2\quad x\quad dx.$

81. $\displaystyle\int\frac{dx}{(a^2+x {2})^2}$

82. $\displaystyle\int\sqrt{1-senx dx}.$

83. $\displaystyle\int\text{arctg}\sqrt{x}dx.$

84. $\displaystyle\int sen\sqrt{x+1}dx.$

85. $\displaystyle\int\frac{\sqrt{x^3-2}}{x}dx.$

86. $\displaystyle\int log(x+\sqrt{x^2-1})dx.$

87. $\displaystyle\int log(x+\sqrt{x})dx.$

88. $\displaystyle\int\frac{dx}{x-x^{3/5}}.$

89. $\displaystyle\int\frac{dx}{1+sen x}.$

90. $\displaystyle\int\frac{dx}{3+5senx}.$

Evaluar la integral utilizando la integración por partes con las elecciones indicadas de $u$ y $dv$.

1. $\displaystyle\int x \ln x dx;\quad u=\ln x,\quad dv=x dx$

2. $\displaystyle\int\theta\sec^2\theta d\theta;\quad u=\theta,\quad dv=\sec^2\theta d\theta$

Evaluar la integral

3. $\displaystyle\int x\cos 5x dx$

4. $\displaystyle\int xe^{-x}dx$

5. $\displaystyle\int re^{r/2}dr$

6. $\displaystyle\int t\sin 2tdt$

7. $\displaystyle\int x^2\sin\pi x dx$

8. $\displaystyle\int x^2\cos mx dx$

9. $\displaystyle\int \ln(2x+1)dx$

10. $\displaystyle\int \sin^{-1}xdx$

11. $\displaystyle\int\text{arc}\tan4tdt$

12. $\displaystyle\int p^{5}\ln pdp$

13. $\displaystyle\int(\ln x^2)dx$

14. $\displaystyle\int t^3e^tdt$

15. $\displaystyle\int e^{2\theta}\sin 3\theta d\theta$

16. $\displaystyle\int e^{\theta}\cos2\theta d\theta$

17. $\displaystyle\int y\sinh y dy$

18. $\displaystyle\int y \cosh ay dy$

19. $\displaystyle\int_0^\pi t\sin3t dt$

20. $\displaystyle\int_0^1(x^2+1)e^{-x}dx$

21. $\displaystyle\int_1^2\frac{\ln x}{x^2}dx$

22. $\displaystyle\int_1^4\sqrt{t}\ln t dt$

23. $\displaystyle\int_0^1\frac{y}{e^{2y}}dy$

24. $\displaystyle\int_{\pi/4}^{\pi/2}x\csc^2xdx$

25. $\displaystyle\int_0^{1/2}\cos^{-1}x dx$

26. $\displaystyle\int_0^1x5^xdx$

27. $\displaystyle\int\cos x \ln(\sin x)dx$

28. $\displaystyle\int_1^{\sqrt{3}}\arctan(1/x)dx$

29. $\displaystyle\int\cos(\ln x)dx$

30. $\displaystyle\int_0^1\frac{r^3}{\sqrt{4+r^2}}dr$

31. $\displaystyle\int_1^2x^4(\ln x)^2dx$

32. $\displaystyle\int_0^te^s\sin(t-s)ds$

Primero realice una sustitución y luego use la integración por partes para evaluar la integral.

33. $\displaystyle\int\sin\sqrt{x}dx$

34. $\displaystyle\int_1^4e^{\sqrt{x}}dx$

35. $\displaystyle\int_{\sqrt{\pi/2}}^{\sqrt{\pi}}\theta^3\cos(\theta^2)d\theta$

36. $\displaystyle\int x^5e^{x^2}dx$

37. $\displaystyle\int x\cos\pi xdx$

38. $\displaystyle\int x^{3/2}\ln x dx$

39. $\displaystyle\int(2x+3)e^x dx$

40. $\displaystyle\int x^3 e^{x^2} dx$

41.

a. Demuestre que:

$\displaystyle\int\sin^2xdx=\frac{x}{2}-\frac{\sin 2x}{4}+C$

b. Use la parte (a) y la fórmula de reducción para evaluar $\displaystyle\int \sin^4x dx.$

42.

a. Demuestre la fórmula de reducción

$\displaystyle\int\cos^nxdx=\frac{1}{n}\cos^{n-1}x\sin x+\frac{n-1}{n}\displaystyle\int \cos^{n-2}xdx$

b. Use la parte (a) para evaluar $\displaystyle\int\cos^2xdx.$

c. Use las partes (a) y (b) para evaluar $\displaystyle\int\cos^4xdx.$

43.

a. Demuestre que:

$$\displaystyle\int_0^{\pi/2}\sin^nxdx=\frac{n-1}{n}\displaystyle\int_0^{\pi/2}\sin^{n-2}xdx$$
Cuando $n\ge2$ es un numero entero.

b. Use la parte (a) para evaluar, $\displaystyle\int_0^{\pi/2}\sin^3x dx\quad y\quad \displaystyle\int_0^{\pi/2}\sin^5dx.$

c. Use la parte (a) para mostrar que, para las potencias impares del seno,

$$\displaystyle\int_0^{\pi/2}\sin^{2n+1}xdx=\frac{2.4.6.....2n}{3.5.7.....(2n+1)}$$
44. Demuestre que, incluso para las potencias del seno:

$$\displaystyle\int_0^{\pi/2}\sin^{2n}xdx=\frac{1.3.5.....(2n-1)}{2.4.6.....2n}\frac{\pi}{2}$$

Use la integración por partes para probar la fórmula de reducción

45. $\displaystyle\int(\ln x)^ndx=x(\ln x)^n-n\displaystyle\int(\ln x)^{n-1}dx$

46. $\displaystyle\int x^ne^xdx=x^ne^x-n\displaystyle\int x^{n-1}e^xdx$

47. $\displaystyle\int(x^2+a^2)^ndx =\frac{x(x^2+a^2)^n}{2n+1}+\frac{2na^2}{2n+1}\displaystyle\int(x^2+a^2)^{n-1}dx\quad (n\ne-\frac{1}{2})$

48. $\displaystyle\int\sec^nx dx=\frac{\tan x\sec^{n-2}x}{n-1}+\frac{n-1}{n-1}\displaystyle\int\sec^{n-2}xdx\quad (n\ne1)$

49. Usa el ejercicio 45 para encontrar $\displaystyle\int(\ln x)^3dx.$

50. Usa el ejercicio 46 para encontrar $\displaystyle\int x^4e^xdx.$

Encuentra el área de la región delimitada por las curvas dadas.

51. $y=xe^{-0,4x},\quad y=0,\quad x=5$

52. $y=5\ln x,\quad y=x\ln x$

\newpage

Integrales trigonométricas

Evaluar la integral.

1. $\displaystyle\int\sin^3x\cos^2xdx$

2. $\displaystyle\int\sin^6x\cos^3xdx$

3. $\displaystyle\int\_{\pi/2}^{3\pi/4}\sin^5x\cos^3xdx$

4. $\displaystyle\int_0^{\pi/2}\cos^5xdx$

5. $\displaystyle\int\cos^5x\sin^4xdx$

6. $\displaystyle\int\\sin^3(mx)dx$

7. $\displaystyle\int_0^{\pi/2}\cos^2\theta d\theta$

8. $\displaystyle\int_0^{\pi/2}\sin^2(2\theta)d\theta$

9. $\displaystyle\int_0^{\pi}\sin^4(3t)dt$

10. $\displaystyle\int_0^{\pi}\cos^6\theta d\theta$

11. $\displaystyle\int(1+\cos\theta)^2d\theta$

12. $\displaystyle\int x\cos^2xdx$

13. $\displaystyle\int_0^{\pi/4}\sin^4xcos^2xdx$

14. $\displaystyle\int_0^{\pi/2}\sin^2x\cos^2xdx$

15. $\displaystyle\int\sin^3x\sqrt{\cos x}dx$

16. $\displaystyle\int\cos\theta\cos^5(sin \theta)d\theta$

17. $\displaystyle\int\cos^2x\tan^3xdx$

18. $\displaystyle\int\cot^5\theta\sin^4\theta d\theta$

19. $\displaystyle\int\frac{1-\sin x}{\cos x }dx$

20. $\displaystyle\int\cos^2 x\sin 2xdx$

21. $\displaystyle\int\sec^2x\tan x dx$

22. $\displaystyle\int_0^{\pi/2}\sec^4(t/2)dt$

23. $\displaystyle\int\tan^2xdx$

24. $\displaystyle\int\tan^4xdx$

25. $\displaystyle\int\sec^6tdt$

26. $\displaystyle\int_0^{\pi/4}\sec^4\theta\tan^4\theta d\theta$

27. $\displaystyle\int_0^{\pi/3}\tan^5\sec^4xdx$

28. $\displaystyle\int\tan^3(2x)\sec^5(2x)dx$

29. $\displaystyle\int\tan^3\sec xdx$

30. $\displaystyle\int_0^{\pi/3}\tan^5x\sec^6xdx$

31. $\displaystyle\int\tan^5x dx$

32. $\displaystyle\int\tan^6(ay)dy$

33. $\displaystyle\int\frac{\tan^3\theta}{\cos^4\theta}d\theta$

34. $\displaystyle\int\tan^2x \sec xdx$

35. $\displaystyle\int_{\pi/6}^{\pi/2}\cot^2 x dx$

36. $\displaystyle\int_{\pi/4}^{\pi/2}\cot^3x dx$

37. $\displaystyle\int\cot^3\alpha\csc^3\alpha d\alpha$

38. $\displaystyle\int\csc^4x\cot^5x dx$

39. $\displaystyle\int\csc x dx$

40. $\displaystyle\int_{\pi/6}^{\pi/3}\csc^3x dx$

41. $\displaystyle\int\sin 5x\sin 2x dx$

42. $\displaystyle\int\sin 3x\cos x dx$

43. $\displaystyle\int\cos 7\theta\cos 5\theta d\theta$

44. $\displaystyle\int\frac{\cos x+\sin x}{\sin 2x}dx$

45. $\displaystyle\int\frac{1-\tan^2x}{\sec^2x}dx$

46. $\displaystyle\int\frac{dx}{\cos x-1}$

47. $\displaystyle\int t\sec^2(t^2)\tan^4(t^2)dt$

48. Si $\displaystyle\int_0^{\pi/4}\tan^6x\sec xdx=I$ exprese el valor de $\displaystyle\int_0^{\pi/4}\tan^8x \sec x dx$ en terminos de $I$.

Evalúa la integral indefinida. Ilustre y compruebe que su respuesta es razonable, graficando tanto el integrando como su antiderivada (tomando $C=0$)

49. $\displaystyle\int\sin^5xdx$

50. $\displaystyle\int\sin^4x\cos^4xdx$

51. $\displaystyle\int\sin 3x\sin 6x dx$

52. $\displaystyle\int\sec^4 \frac{x}{2}dx$

Evaluar la integral usando la sustitución trigonométrica indicada. Dibuje y etiquete el triángulo rectángulo asociado.

1. $\displaystyle\int\frac{1}{x^2\sqrt{x^2-9}}dx;\quad x=3\sec \theta$

2. $\displaystyle\int x^3\sqrt{9-x^2}dx;\quad x=3\sin\theta$

3. $\displaystyle\int\frac{x^3}{\sqrt{x^2+9}}dx;\quad x=3\tan\theta$

4. $\displaystyle\int_0^{2\sqrt{3}}\frac{x^3}{\sqrt{16-x^2}}dx$

5. $\displaystyle\int_{\sqrt{2}}^2\frac{1}{t^3\sqrt{t^2-1}}dt$

6. $\displaystyle\int_0^2x^3\sqrt{x^2+4}dx$

7. $\displaystyle\int\frac{1}{x^2\sqrt{25-x^2}}dx$

8. $\displaystyle\int\frac{\sqrt{x^2-a^2}}{x^4}dx$

9. $\displaystyle\int\frac{dx}{\sqrt{x^2+16}}$

10. $\displaystyle\int\frac{t^5}{\sqrt{t^2+2}}dt$

11. $\displaystyle\int\sqrt{1-4x^2}dx$

12. $\displaystyle\int_0^1 x\sqrt{x^2+4}dx$

13. $\displaystyle\int\frac{x^2-9}{x^3}dx$

14. $\displaystyle\int\frac{du}{u\sqrt{5-u^2}}$

15. $\displaystyle\int\frac{x^2}{(a^2-x^2)^{3/2}}dx$

16. $\displaystyle\int\frac{dx}{x^2\sqrt{16x^2-9}}$

17. $\displaystyle\int\frac{x}{\sqrt{x^2-7}}dx$

18. $\displaystyle\int\frac{dx}{[(ax)^2-b^2]^{3/2}}$

19. $\displaystyle\int\frac{\sqrt{1+x^2}}{x}dx$

20. $\displaystyle\int\frac{t}{\sqrt{25-t^2}}dt$

21. $\displaystyle\int_0^{2/3}x^3\sqrt{4-9x^2}dx$

22. $\displaystyle\int_0^1\sqrt{x^2+1}dx$

23. $\displaystyle\int\sqrt{5+4x-x^2}dx$

24. $\displaystyle\int\frac{dt}{\sqrt{t^2-6t+13}}$

25. $\displaystyle\int\frac{1}{\sqrt{9x^2+6x-8}}dx$

26. $\displaystyle\int\frac{x2}{\sqrt{4x-x^2}}dx$

27. $\displaystyle\int\frac{dx}{(x2^+2x+2)^2}$

28. $\displaystyle\int\frac{dx}{(5-4x-x^2)^{5/2}}$

29. $\displaystyle\int x\sqrt{1-x^4}dx$

30. $\displaystyle\int_0^{\pi/2}\frac{\sqrt{\text{cos}t}}{\sqrt{1+\text{sin}^2t}}dt$

31. 

a) Use la sustitución trigonométrica para mostrar que

$\displaystyle\int\frac{dx}{\sqrt{x^2+a^2}}=\ln (x+\sqrt{x^2+a^2})+C$

b)Usa la sustitución hiperbólica $x=a \sin h t$ para mostrar que

$\displaystyle\int\frac{dx}{\sqrt{x^2+a^2}}=\sin h^{-1}\left(\frac{x}{a}\right)+ C$

Evaluar la integral

7. $\displaystyle\int\frac{x}{x-6}dx$

8. $\displaystyle\int\frac{r^2}{r+4}dr$

9. $\displaystyle\int\frac{x-9}{(x+5)(x-2)}dx$

10. $\displaystyle\int\frac{1}{(t+4)(t-1)}dt$

11. $\displaystyle\int_2^3\frac{1}{x^2-1}dx$

12. $\displaystyle\int_0^1\frac{x-1}{x^2+3x+2}dx$

13. $\displaystyle\int\frac{ax}{x^2-bx}dx$

14. $\displaystyle\int\frac{1}{(x+a)(x+b)}dx$

15. $\displaystyle\int_0^1\frac{2x+3}{(x+1)^2}dx$

16. $\displaystyle\int_0^1\frac{x^3-4x-10}{x^2-x-6}dx$

17. $\displaystyle\int_1^2\frac{4y2^-7y-12}{y(y+2)(y-3)}dy$

18. $\displaystyle\int\frac{x2^+2x-1}{x^3-x}dx$

19. $\displaystyle\int\frac{1}{(x+5)^2(x-1)}dx$

20. $\displaystyle\int\frac{x^2}{(x-3)(x+2)^2}dx$

21. $\displaystyle\int\frac{5x^2+3x-2}{x^3+2x^2}dx$

22. $\displaystyle\int\frac{ds}{s^2(s-1)^2}$

23. $\displaystyle\int\frac{x^2}{(x+1)^3}dx$

24. $\displaystyle\int\frac{x^3}{(x+1)^3}dx$

25. $\displaystyle\int\frac{10}{(x-1)(x^2+9)}dx$

26. $\displaystyle\int\frac{x^2-x+6}{x^3+3x}dx$

27. $\displaystyle\int\frac{x^3+x^2+2x+1}{(x^2+1)(x^2+2)}dx$

28. $\displaystyle\int\frac{x^2-2x-1}{(x-1)^2(x^2+1)}dx$

29. $\displaystyle\int\frac{x+4}{x^2+2x+5}dx$

30. $\displaystyle\int\frac{x3^-2x^2+x+1}{x^4+5x^2+4}dx$

31. $\displaystyle\int\frac{1}{x^3-1}dx$

32. $\displaystyle\int_0^1\frac{x}{x^2+4x+13}dx$

33. $\displaystyle\int_2^5\frac{x^2+2x}{x^3+3x^2+4}dx$

34. $\displaystyle\int\frac{x^3}{x^3+1}dx$

35. $\displaystyle\int\frac{dx}{x^4-x^2}$

36. $\displaystyle\int_0^1\frac{2x^3+5x}{x^4+5x^2+4}dx$

37. $\displaystyle\int\frac{x-3}{(x^2+2x+4)^2}dx$

38. $\displaystyle\int\frac{x^4+1}{x(x^2+1)^2}dx$

Haga una sustitución para expresar el integrando como una función racional y luego evalúe la integral.

39. $\displaystyle\int\frac{1}{x\sqrt{x+1}}dx$

40. $\displaystyle\int\frac{1}{x-\sqrt{x+2}}dx$

41. $\displaystyle\int_9^{16}\frac{\sqrt{x}}{x-4}dx$

42. $\displaystyle\int_0^1\frac{1}{1+\sqrt[3]{x}}dx$

43. $\displaystyle\int\frac{x^3}{\sqrt[3]{x^2+1}}dx$

44. $\displaystyle\int_{1/3}^3\frac{\sqrt{x}}{x^2+x}dx$

45. $\displaystyle\int\frac{1}{\sqrt{x}-\sqrt[3]{x}}dx$ Sugerencia: Sustituto $\mu=\sqrt[6]{x}.$ 

46. $\displaystyle\int\frac{1}{\sqrt[3]{x}+\sqrt[4]{x}}dx$ Sugerencia: Sustituto $\mu=\sqrt[12]{x}.$

47. $\displaystyle\int\frac{e^{2x}}{e^{2x}+3e^x+2}dx$

48. $\displaystyle\int\frac{\text{cos}x}{\text{sin}^2x+\text{sin}x}dx$

Use la integración por partes, junto con las técnicas de esta sección, para evaluar la integral.

49. $\displaystyle\int\ln (x^2-x+2)dx$

50. $\displaystyle\int x\tan^{-1}xdx$

